fix(umc-diagnostics): Fix LDAP schema registration
Call shell library with correct arguments:

> + ucs_registerLDAPSchema /tmp/root/tmp8h9s0gue/univention-corporate-client.schema
> ...
> Usage: ucs_registerLDAPExtension [options]
>
> ucs_registerLDAPExtension: error: --schema: file does not exist:

Fix broken test, which should have detected this.

Always delete schema file after test; depending on the phase of the test
the file is in different locations:

1. `ucs_registerLDAPSchema` installs to
   /var/lib/univention-ldap/local-schema/.

2. UMC diagnostics module "60_old_schema_registration" then calls
   `ucs_unregisterLDAPExtension` to "move" it to LDAP (but fails because
   of Bug #57279)

3. `ucs_unregisterLDAPExtension` must be used to remove it from LDAP.

4. But also make sure it is removed from `local-schema/`.

> The schema entry was found: ( 1.3.6.1.4.1.10176.200.10999.66345 NAME 'univentionFreeAttribute66345' DESC ' unused custom attribute 66345 ' EQUALITY caseExactMatch SUBSTR caseIgnoreSubstringsMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 )

This is still the schema locally included from `local-schema/`.

> ...
> + ucs_unregisterLDAPExtension --schema univention-corporate-client
> + python3 -m univention.lib.ldap_extension ucs_unregisterLDAPExtension --schema univention-corporate-client
> ERROR: Object not found in UDM.

This fails as the schema was never moved to LDAP. Subsequently the
schema will remain even after test!

Use temporary file with unpredictable name.

Bug #57279
Issue univention/ucs#1854