Bug #42849 udm: Fix policy listing for dhcp/host entries
LB=$(ucr get ldap/base) R=$RANDOM
udm dhcp/service create --position "$LB" --set service="service$R"
udm dhcp/host create --superordinate "cn=service$R,$LB" --set hwaddress='ethernet 000000000000' --set host="host$R"
udm dhcp/host list --superordinate "cn=service$R,$LB" --policies 0

> Information provided is not sufficient: The DN must be underneath of the superordinate.
UDM finds the subnet from cn=dhcp,$LB, which is not underneath this new
2nd service.

udm dhcp/subnet create --superordinate "cn=service$R,$LB" --set subnet=192.0.2.0 --set subnetmask=24
udm dhcp/host list --superordinate "cn=service$R,$LB" --policies 0

> Traceback (most recent call last):
>   File "/usr/share/pyshared/univention/admincli/admin.py", line 1126, in <module>
>     print '\n'.join(doit(sys.argv))
>   File "/usr/share/pyshared/univention/admincli/admin.py", line 394, in doit
>     out=_doit(arglist)
>   File "/usr/share/pyshared/univention/admincli/admin.py", line 1057, in _doit
>     if univention.admin.ipaddress.ip_is_in_network(subnet['subnet'], subnet['subnetmask'], object['fixedaddress'][0]):
> IndexError: list index out of range
A dhcp/host entry can also have none or multiple IP addresses

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@74103 1b283449-9f2f-0410-b571-8eb228e1a901