Bug #52850: 09_updater/90_ucr ensure dpkg-reconfiguration does not break slapd.conf
UNIVENTION_BASECONF="$tmp" dpkg-reconfigure univention-updater || :
dpkg-reconfigure univention-updater

This causes a UCR commit of multiple configfiles using a empty UCR config:

File: /etc/apt/sources.list.d/15_ucs-online-version.list
File: /etc/issue
File: /etc/lsb-release
File: /etc/apt/sources.list.d/20_ucs-online-component.list
File: /etc/cron.d/univention-updater-check
File: /etc/apt/mirror.list
File: /etc/apt/apt.conf.d/55user_agent
File: /etc/issue.net
File: /etc/welcome.msg
File: /etc/apache2/ucs-sites.conf.d/univention-portal.conf
Script: /etc/univention/templates/scripts/symlink_portal
File: /etc/apache2/sites-available/univention-portal.conf
Multifile: /etc/ldap/slapd.conf
File: /usr/lib/univention-portal/config/config.json
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
TypeError: can only concatenate str (not "NoneType") to str
File: /etc/logrotate.d/univention-updater
File: /etc/apt/sources.list.d/15_ucs-online-version.list
File: /etc/apt/sources.list.d/20_ucs-online-component.list
File: /etc/apt/mirror.list
File: /etc/apt/apt.conf.d/55user_agent
File: /etc/cron.d/univention-updater-check

I guess: As the UCR variables which are previously already set aren't changed the second "dpkg-reconfigure univention-updater" doesn't commit these templates again so that we are left with a broken slapd.conf, broken /usr/lib/univention-portal/config/config.json and possibly more.

The following test case 10_ldap/10slapd_stop_start fails then:

> Check if services can be correctly stopped
> Check if we can test the service "slapd" on server role "domaincontroller_master"       Yes
> Trying to stop service slapd    Stopping slapd (via systemctl): slapd.service.
> Done
> Has the service been stopped?   Ok
> Job for slapd.service failed because the control process exited with error code.
> See "systemctl status slapd.service" and "journalctl -xe" for details.
> Trying to start service "slapd" Starting slapd (via systemctl): slapd.service failed!
> Done
> Is this service running?        Error

slapd[12002]: 6030e97e /etc/ldap/slapd.conf: line 33: keyword <loglevel> missing <level> argument slapschema: bad configuration file!.