Bug #51508: add more verbose error logging
The migration to Python 3 might lead to bytes in the response. This
cannot be JSON encoded. Therefore log the data.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 344, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 247, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/__init__.py", line 122, in _decoarated
    self.finished(request.id, ret)
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 465, in finished
    self.result(res)
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 469, in result
    self.signal_emit('success', response)
  File "/usr/lib/python3/dist-packages/notifier/signals.py", line 87, in signal_emit
    self.__signals[signal].emit(*args)
  File "/usr/lib/python3/dist-packages/notifier/signals.py", line 50, in emit
    if cb(*args):
  File "/usr/lib/python3/dist-packages/notifier/__init__.py", line 105, in __call__
    return self._function(*tmp, **self._kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 141, in _reply
    self.response(msg)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 376, in response
    self.__queue += bytes(msg)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 342, in __bytes__
    return Message._formattedMessage(self._id, self._type, self.mimetype, self.command, body, self.arguments)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 122, in _formattedMessage
    data = json.dumps(body)
  File "/usr/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable