test(udm): xfail map-county-to-st
Depending on UCRV directory/manager/web/modules/users/user/map-country-to-st tests fail

> AssertionError: assert '(&(univentio...nal))(c=foo))' == '(&(univention...al))(st=foo))'
>   - (&(univentionObjectType=users/user)(!(uidNumber=0))(!(univentionObjectFlag=functional))(c=foo))
>   ?                                                                                         ^
>   + (&(univentionObjectType=users/user)(!(uidNumber=0))(!(univentionObjectFlag=functional))(st=foo))
>   ?                                                                                         ^^

"userexpiry" depends on timezone of test environment.

Bug #50073