Bug #52919: fix traceback in hosts.d/00-base
Sort explicit by ip version instead of implicit by name

Multifile: /etc/hosts
Traceback (most recent call last):
  File "<stdin>", line 41, in <module>
  TypeError: '<' not supported between instances of 'str' and 'NoneType'