feat(ad-connector): fix regression for windowscomputer
due to copying too much code from S4-Connector to AD-Connector.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/connector/__init__.py", line 1412, in sync_to_ucs
    post_ucs_modify_function(self, property_type, object)
  File "/usr/lib/python3/dist-packages/univention/connector/ad/__init__.py", line 76, in group_members_sync_to_ucs
    return connector.group_members_sync_to_ucs(key, object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/connector/ad/__init__.py", line 1611, in group_members_sync_to_ucs
    uniqueMember_add = add_members['user'] + add_members['group'] + add_members['unknown'] + add_members['windowscomputer']
                                                                                             ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'windowscomputer'

Bug #58644