refactor[test/data]: Remove hashing code
as it is unused and the current code is not working anyway

Also fix opening with context
> Traceback (most recent call last):
>   File "/usr/sbin/ucs-test", line 210, in <module>
>     sys.exit(main())
>   File "/usr/sbin/ucs-test", line 203, in main
>     return test_set.run_tests(options.filter, options.dry, options.hold)
>   File "/usr/sbin/ucs-test", line 130, in run_tests
>     test_case = TestCase(fname).load()
>   File "/usr/lib/python3/dist-packages/univention/testing/data.py", line 536, in load
>     with open(self.filename, 'rb') as tc_file:
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ucs-test/21_appcenter-uninstall/10_user_creation'

Bug #53768
Fixes: 42f5265fc7acd9b607721b4c733f20204bb32ffd