test(self-service): add missing dependency
Traceback (most recent call last):
  File "/usr/share/ucs-test/83_self_service/01_test_reset_via_email.py", line 15, in <module>
    from test_self_service import capture_mails, self_service_user
  File "/usr/share/ucs-test/83_self_service/test_self_service.py", line 1, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'

Bug #59418