fix[dhcp]: Fix DHCP network creation
Fallback to network- and broadcast-address from network if not
explicitly set via UCR: Newer D-I net-installer no longer sets them.

> Traceback (most recent call last):
>   File "/usr/lib/univention-dhcp/create-subnets", line 128, in <module>
>     main()
>   File "/usr/lib/univention-dhcp/create-subnets", line 60, in main
>     create(opt, ucr, iface, lo, mod)
>   File "/usr/lib/univention-dhcp/create-subnets", line 116, in create
>     obj["subnet"] = network
>   File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 446, in __setitem__
>     raise univention.admin.uexceptions.valueInvalidSyntax("%s: %s" % (self.descriptions[key].short_description, err), property=key)
> univention.admin.uexceptions.valueInvalidSyntax: Subnet address: Not a valid IP address!

(Pdb) break 111
(Pdb) run
(Pdb) p addr
IPv4Interface('10.200.17.38/24')
(Pdb) p iface.network
None
(Pdb) p iface.broadcast
None
(Pdb) p addr.broadcast
*** AttributeError: 'IPv4Interface' object has no attribute 'broadcast'

Bug #53074