Bug #49508 dojo: Change Java dependency to default-jre-headless
OpenJDK-7 is out-of-maintenance and buggy.
No JDK is needed, the JRE is enough.
Headless is sufficient, but still required:
+ node /usr/share/univention-dojo/util/buildscripts/../../dojo/dojo.js load=build profile=build_profile.js version=3.0.5-14
...
> processing profile resource /root/univention-web/tmp/dompurify/package.js
> discovering resources...
> starting reading resources...
> starting processing raw resource content...
> starting tokenizing resource...
> starting processing resource tokens...
> starting parsing resource...
> { [Error: spawn java ENOENT]
>   code: 'ENOENT',
>   errno: 'ENOENT',
>   syscall: 'spawn java',
>   path: 'java',
>   spawnargs:
>    [ '-cp',
>      '/usr/share/univention-dojo/util/closureCompiler/compiler.jar:/usr/share/univention-dojo/util/shrinksafe/js.jar:/usr/share/univention-dojo/util/shrinksafe/shrinksafe.jar',
>      'org.mozilla.javascript.tools.shell.Main',
>      '/usr/share/univention-dojo/util/build/optimizeRunner.js' ] }
> Error: spawn java ENOENT
>     at exports._errnoException (util.js:907:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
>     at onErrorNT (internal/child_process.js:363:16)
>     at nextTickCallbackWith2Args (node.js:511:9)
>     at process._tickCallback (node.js:425:17)
>     at Function.Module.runMain (module.js:443:11)
>     at startup (node.js:140:18)
>     at node.js:1043:3

Add missing Perl dependency.