Bug #54561: Return an empty list instead of None if key doesn't exist in cache
Traceback (most recent call last):
  File "/usr/lib/univention-directory-listener/system/office365-group.py", line 133, in handler
    ol.create_groups(dn, new)
  File "/usr/lib/python2.7/dist-packages/univention/office365/listener.py", line 389, in create_groups
    if self.udm.group_in_azure(dn):
  File "/usr/lib/python2.7/dist-packages/univention/office365/udm_helper.py", line 146, in group_in_azure
    alias_users = set(x.lower() for x in univentionOffice365ADConnectionAlias.get(self.adconnection_alias))
TypeError: 'NoneType' object is not iterable