Bug #37931 test: Fix broken tests
CRITICAL:test:Failed to load test
"/usr/share/ucs-test/60_umc-system/34_userphoto.jpeg": Missing hash-bang

Traceback (most recent call last):
  File "/usr/sbin/ucs-test", line 177, in <module>
    main()
  File "/usr/sbin/ucs-test", line 172, in main
    test_set.run_tests(options.filter, options.dry, options.hold)
  File "/usr/sbin/ucs-test", line 112, in run_tests
    test_case = TestCase().load(fname)
  File "/usr/lib/pymodules/python2.7/univention/testing/data.py", line 520, in load
    header = yaml.load(reader) or {}
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python2.7/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/usr/lib/python2.7/dist-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<file>", line 1, column 54

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-2@62200 1b283449-9f2f-0410-b571-8eb228e1a901