Bug #51588 up: add more python 3 compatibility
NOTE: HTTP basic auth credentials are (correctly) decoded as ISO8859-1 now.
Previously it was only used with bytestring, so Python 2 might decoded
it automatically to UTF-8?

Configuration error: component not found: 5.0-0-errata-test
An error occurred during the repository check. The error message:

Traceback (most recent call last):
  File "/tmp/py3.in", line 15, in <module>
    print(updater.print_component_repositories())
  File "/usr/lib/python3/dist-packages/univention/updater/tools.py", line 1854, in print_component_repositories
    repos = self.get_component_repositories(component, versions, clean, for_mirror_list=for_mirror_list)
  File "/usr/lib/python3/dist-packages/univention/updater/tools.py", line 1770, in get_component_repositories
    if isinstance(version, basestring):
NameError: name 'basestring' is not defined