perf(udm-computers): make removal from groups after removing computer object fast
Traceback (most recent call last):
  File "/usr/share/ucs-test/59_udm/50_test_udm_api.py", line 594, in test_cleanup
    ubuntu.delete()
  File "/usr/lib/python3/dist-packages/univention/udm/modules/generic.py", line 214, in delete
    self._orig_udm_object.remove(remove_childs=remove_childs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1068, in remove
    return self._remove(remove_childs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1787, in _remove
    self._ldap_post_remove()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/computers/__base.py", line 163, in _ldap_post_remove
    super()._ldap_post_remove()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 3464, in _ldap_post_remove
    groupObject.fast_member_remove([self.dn], [x.decode('UTF-8') for x in self.oldattr.get('uid', [])], ignore_license=True)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/groups/group.py", line 395, in fast_member_remove
    return self.lo.authz_connection.modify(self.dn, ml, exceptions=True, ignore_license=ignore_license)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 664, in modify
    return self.lo.modify(dn, changes, serverctrls=serverctrls, response=response, rename_callback=rename_callback)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 166, in _decorated
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 719, in modify
    self.modify_ext_s(dn, ml, serverctrls=serverctrls, response=response)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 166, in _decorated
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 778, in modify_ext_s
    _rtype, _rdata, _rmsgid, resp_ctrls = self.lo.modify_ext_s(dn, ml, serverctrls=serverctrls)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1024, in modify_ext_s
    return self._apply_method_s(SimpleLDAPObject.modify_ext_s,*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 968, in _apply_method_s
    return func(self,*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 400, in modify_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 543, in result3
    resp_type, resp_data, resp_msgid, decoded_resp_ctrls, retoid, retval = self.result4(
                                                                           ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 553, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 128, in _ldap_call
    result = func(*args,**kwargs)
             ^^^^^^^^^^^^^^^^^^^^
ldap.NO_SUCH_ATTRIBUTE: {'msgtype': 103, 'msgid': 168, 'result': 16, 'desc': 'No such attribute', 'ctrls': [], 'info': 'modify/delete: uniqueMember: no such value'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/udm/modules/generic.py", line 214, in delete
    self._orig_udm_object.remove(remove_childs=remove_childs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1060, in remove
    raise univention.admin.uexceptions.noObject(self.dn)
univention.admin.uexceptions.noObject: No such object: cn=ubuntu,cn=computers,dc=ucs,dc=test.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/ucs-test/59_udm/50_test_udm_api.py", line 597, in test_cleanup
    ubuntu.delete()
  File "/usr/lib/python3/dist-packages/univention/udm/modules/generic.py", line 216, in delete
    raise DeleteError(
univention.udm.exceptions.DeleteError: Error deleting 'computers/ubuntu' object 'cn=ubuntu,cn=computers,dc=ucs,dc=test': No such object: cn=ubuntu,cn=computers,dc=ucs,dc=test.

Bug #58899