Bug #43432: fix disabling of StartTLS for S4-Connector tests
The old code `self.ssl = configRegistry.get('%s/s4/ldap/ssl', "no")`
always was `False` due to missing `%`-interpolation.

In our Jenkins instances we have to disable TLS as it fails with:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/testing/ldap_glue.py", line 92, in connect
    self.lo.start_tls_s()
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 864, in start_tls_s
    return self._ldap_call(self._l.start_tls_s)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 329, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
ldap.CONNECT_ERROR: {'desc': 'Connect error', 'info': 'TLS: hostname does not match CN in peer certificate'}