fix(udm): fix circular import
Traceback:
/usr/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
unittests/test_udm_filters.py:32: in <module>
    import univention.admin.modules
modules/univention/admin/__init__.py:47: in <module>
    import univention.admin.handlers
modules/univention/admin/handlers/__init__.py:60: in <module>
    import univention.admin.allocators
modules/univention/admin/allocators.py:43: in <module>
    from univention.admin import configRegistry, localization
E   ImportError: cannot import name 'configRegistry' from partially initialized module 'univention.admin' (most likely due to a circular import) (/var/build/temp/tmp.Szboqt6pk3/univention-directory-manager-modules-17.0.4/modules/univention/admin/__init__.py)

Bug #56604