fixup! Bug #52258: migate nagios listener to Python 3
Traceback (most recent call last):
  File "/usr/lib/univention-directory-listener/system/nagios-client.py", line 173, in handler
    writeConfig(fqdn, new)
  File "/usr/lib/univention-directory-listener/system/nagios-client.py", line 103, in writeConfig
    cmdline = replaceArguments(cmdline, new['univentionNagiosCheckArgs'][0].split(b'!'))
  File "/usr/lib/univention-directory-listener/system/nagios-client.py", line 80, in replaceArguments
    cmdline = re.sub(r'\$ARG%s\$'.encode('ASCII') % (i + 1), args[i], cmdline)
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'int'