Bug #51570: fix closing of file descriptors
Workaround python-daemon issue

Interner Server-Fehler in "appcenter/docker/progress".
Request: appcenter/docker/progress

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/management/console/base.py", line 359, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/base.py", line 262, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/decorators.py", line 321, in _response
    result = _multi_response(self, request)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/decorators.py", line 181, in _response
    return function(self, request)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/decorators.py", line 443, in _response
    return list(function(self, iterator, *nones))
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/decorators.py", line 289, in _fake_func
    yield function(self, *args)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/mixins.py", line 158, in progress
    ret = progress_obj.poll()
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/mixins.py", line 102, in poll
    six.reraise(self.exc_info[1], None, self.exc_info[2])
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/decorators.py", line 312, in _thread
    result = _multi_response(self, request)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/decorators.py", line 181, in _response
    return function(self, request)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/decorators.py", line 443, in _response
    return list(function(self, iterator, *nones))
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/decorators.py", line 289, in _fake_func
    yield function(self, *args)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/appcenter/__init__.py", line 274, in run
    ret[app.id] = self._run_local(app, action, _settings, progress)
  File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/appcenter/__init__.py", line 314, in _run_local
    success = action.call(app=[app], username=self.username, password=self.password, **kwargs)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/__init__.py", line 174, in call
    return obj.call_with_namespace(namespace)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/__init__.py", line 180, in call_with_namespace
    result = self.main(namespace)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/install.py", line 87, in main
    return self.do_it(args)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/install_base.py", line 141, in do_it
    success = self.do_it_once(app, args)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/install.py", line 200, in do_it_once
    return super(Install, self).do_it_once(app, args)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/install_base.py", line 185, in do_it_once
    self._do_it(app, args)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/docker_install.py", line 71, in _do_it
    ret = super(Install, self)._do_it(app, args)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/install.py", line 112, in _do_it
    self._register_attributes(app, args)
  File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/register.py", line 230, in _register_attributes
    schema_obj.register(schema_file, opts, udm_passthrough_options)
  File "/usr/lib/python2.7/dist-packages/univention/lib/ldap_extension.py", line 411, in register
    print("INFO: No change of core data of object %s." % (self.objectname,), file=sys.stderr)
IOError: [Errno 107] Der Socket ist nicht verbunden