Bug #49129 ucr: py3: Fix configparser
The Python 3 parser for '.ini' files is more strict then the Python 2
variant:

> configparser.DuplicateSectionError: While reading from '/etc/univention/registry.info/variables/univention-samba4.cfg' [line 241]: section 'samba/share/home' already exists
...
> configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%U' wird zur Laufzeit auf den aktuellen Benutzer expandiert."

Disable interpolation and switch to non-strict mode.