Bug #42114: fixup error in sanization if PatternSanitizer is used
umc-command -U Administrator -P univention setup/lang/locales -o 'pattern=*'

Execution of command 'setup/lang/locales wizard' has failed:

Traceback (most recent call last):
  File "%PY2.7%/univention/management/console/base.py", line 249, in execute
    function.__func__(self, request, *args, **kwargs)
  File "%PY2.7%/univention/management/console/modules/decorators.py", line 192, in _response
    return function(self, request)
  File "%PY2.7%/univention/management/console/modules/decorators.py", line 318, in _response
    result = _multi_response(self, request)
  File "%PY2.7%/univention/management/console/modules/decorators.py", line 183, in _response
    request.options = sanitizer.sanitize(options_name, {options_name: request.options})
  File "%PY2.7%/univention/management/console/modules/sanitizers.py", line 186, in sanitize
    new_value = self._sanitize(value, name, further_arguments)
  File "%PY2.7%/univention/management/console/modules/sanitizers.py", line 325, in _sanitize
    altered_value.append(self.sanitizer.sanitize(name, {name: item}))
  File "%PY2.7%/univention/management/console/modules/sanitizers.py", line 186, in sanitize
    new_value = self._sanitize(value, name, further_arguments)
  File "%PY2.7%/univention/management/console/modules/sanitizers.py", line 267, in _sanitize
    altered_value = copy.deepcopy(value)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@77030 1b283449-9f2f-0410-b571-8eb228e1a901