Bug #50648: fix types definition for complex syntaxes without subsyntax_key_value
e.g. portals/entry:link

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2383, in get
    entry = Object.get_representation(objmodule, obj, properties, self.ldap_connection)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2730, in get_representation
    values = dict(decode_properties(module, obj, values))
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 3657, in decode_properties
    yield key, codec.decode_json(value)
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 135, in decode_json
    return self.to_json_type(self.decode(value))
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 118, in decode
    return self.decode_value(value)
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 522, in decode_value
    return [item_type.decode(val) for val in value]
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 522, in <listcomp>
    return [item_type.decode(val) for val in value]
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 118, in decode
    return self.decode_value(value)
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 568, in decode_value
    for item_type, val in zip(self.item_types, value)
TypeError: zip argument #1 must support iteration

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 1456, in get
    model_properties[name] = codec.get_openapi_definition()
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 217, in get_openapi_definition
    return dict((key, value) for key, value in self.openapi_definition().items() if value is not None and value not in (float('inf'), -float('inf')))
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 509, in openapi_definition
    definition['items'] = self.item_type(self.property, self.property_name).get_openapi_definition()
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 217, in get_openapi_definition
    return dict((key, value) for key, value in self.openapi_definition().items() if value is not None and value not in (float('inf'), -float('inf')))
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 579, in openapi_definition
    items = [item.get_openapi_definition() for item in self.item_types]
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 579, in <listcomp>
    items = [item.get_openapi_definition() for item in self.item_types]
TypeError: get_openapi_definition() missing 1 required positional argument: 'self'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 1456, in get
    model_properties[name] = codec.get_openapi_definition()
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 217, in get_openapi_definition
    return dict((key, value) for key, value in self.openapi_definition().items() if value is not None and value not in (float('inf'), -float('inf')))
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 509, in openapi_definition
    definition['items'] = self.item_type(self.property, self.property_name).get_openapi_definition()
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 217, in get_openapi_definition
    return dict((key, value) for key, value in self.openapi_definition().items() if value is not None and value not in (float('inf'), -float('inf')))
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 578, in openapi_definition
    if len(set(items)) == 1:
TypeError: unhashable type: 'dict'