test(end): ignore non-UTF-8 in syslog
```
Traceback (most recent call last):
  File "/usr/share/ucs-test/99_end/06_ldap-index-missing", line 62, in <module>
    for line in fd:
                ^^
  File "<frozen codecs>", line 325, in decode
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 3999-4000: invalid continuation byte
```

Bug #59418