refactor(heimdal): declare PyTypeObject definitions as "extern"
declare PyTypeObject definitions as extern so that during static linking no duplicate definitions are found because since Python 3.9 the definition is added into the .o files.

/usr/bin/ld: build/temp.linux-x86_64-3.9/ccache.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/context.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/creds.o:./creds.h:49: multiple definition of `krb5CredsType'; build/temp.linux-x86_64-3.9/ccache.o:./creds.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/creds.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/creds.o:./principal.h:49: multiple definition of `krb5PrincipalType'; build/temp.linux-x86_64-3.9/ccache.o:./principal.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/enctype.o:./enctype.h:49: multiple definition of `krb5EnctypeType'; build/temp.linux-x86_64-3.9/context.o:./enctype.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/enctype.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/keyblock.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/keyblock.o:./enctype.h:49: multiple definition of `krb5EnctypeType'; build/temp.linux-x86_64-3.9/context.o:./enctype.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/keyblock.o:./keyblock.h:49: multiple definition of `krb5KeyblockType'; build/temp.linux-x86_64-3.9/asn1.o:./keyblock.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/keyblock.o:./salt.h:49: multiple definition of `krb5SaltType'; build/temp.linux-x86_64-3.9/asn1.o:./salt.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/keyblock.o:./principal.h:49: multiple definition of `krb5PrincipalType'; build/temp.linux-x86_64-3.9/ccache.o:./principal.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/keytab.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/module.o:./ccache.h:49: multiple definition of `krb5CcacheType'; build/temp.linux-x86_64-3.9/ccache.o:./ccache.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/module.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/module.o:./creds.h:49: multiple definition of `krb5CredsType'; build/temp.linux-x86_64-3.9/ccache.o:./creds.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/module.o:./enctype.h:49: multiple definition of `krb5EnctypeType'; build/temp.linux-x86_64-3.9/context.o:./enctype.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/module.o:./keyblock.h:49: multiple definition of `krb5KeyblockType'; build/temp.linux-x86_64-3.9/asn1.o:./keyblock.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/module.o:./keytab.h:82: multiple definition of `krb5KeytabType'; build/temp.linux-x86_64-3.9/keytab.o:./keytab.h:82: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/module.o:./principal.h:49: multiple definition of `krb5PrincipalType'; build/temp.linux-x86_64-3.9/ccache.o:./principal.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/module.o:./salt.h:49: multiple definition of `krb5SaltType'; build/temp.linux-x86_64-3.9/asn1.o:./salt.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/principal.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/principal.o:./principal.h:49: multiple definition of `krb5PrincipalType'; build/temp.linux-x86_64-3.9/ccache.o:./principal.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/salt.o:./principal.h:49: multiple definition of `krb5PrincipalType'; build/temp.linux-x86_64-3.9/ccache.o:./principal.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/salt.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/salt.o:./salt.h:49: multiple definition of `krb5SaltType'; build/temp.linux-x86_64-3.9/asn1.o:./salt.h:49: first defined here
/usr/bin/ld: build/temp.linux-x86_64-3.9/ticket.o:./context.h:47: multiple definition of `krb5ContextType'; build/temp.linux-x86_64-3.9/asn1.o:./context.h:47: first defined here
collect2: error: ld returned 1 exit status
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
E: pybuild pybuild:353: build: plugin distutils failed with: exit code=1: /usr/bin/python3 setup.py build·
dh_auto_build: error: pybuild --build -i python{version} -p 3.9 returned exit code 13
make: *** [debian/rules:41: build] Error 25

Bug #55815