fix(udm): handle available timezone namespace in Python 3.7
during the test case 80_docker/73_app_listener_integration.py the PYTHONATH is extended so that a wrong namespace package is detected:

(Pdb) sys.path
['/usr/share', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.7/dist-packages']
(Pdb) zoneinfo
<module 'zoneinfo' (namespace)>
(Pdb) zoneinfo.__spec__
ModuleSpec(name='zoneinfo', loader=<_frozen_importlib_external._NamespaceLoader object at 0x7fd2cdfe66a0>, submodule_search_locations=_NamespacePath(['/usr/share/zoneinfo']))

causing a failed module import:

Traceback (most recent call last):
  File "/usr/share/univention-appcenter-listener-converter", line 203, in main
    find_and_convert_files(app)
  File "/usr/share/univention-appcenter-listener-converter", line 179, in find_and_convert_files
    if convert(app, dumped, filename, lo, pos):
  File "/usr/share/univention-appcenter-listener-converter", line 119, in convert
    objs = search_objects(udm_type, lo, pos, entryUUID=entry_uuid)
  File "/usr/lib/python3/dist-packages/univention/appcenter/udm.py", line 120, in search_objects
    module = _get_module(_module, _lo, _pos)
  File "/usr/lib/python3/dist-packages/univention/appcenter/udm.py", line 66, in _get_module
    _update_modules()
  File "/usr/lib/python3/dist-packages/univention/appcenter/udm.py", line 62, in _update_modules
    udm_modules.update()
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 153, in update
    _walk(root, w_root, w_files)
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 140, in _walk
    m = importlib.import_module('univention.admin.handlers.%s' % (modulepackage,))  # type: Any
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/passwd.py", line 38, in <module>
    import univention.admin.handlers.users.user
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 76, in <module>
    utc = zoneinfo.ZoneInfo('UTC')
AttributeError: module 'zoneinfo' has no attribute 'ZoneInfo'

→ we will ignore that for now.

Bug #55632