Bug #54527: fix 40_mail/29_mail_related_modifications_of_user_objects Python 3 compatibility
Python 2 sent `BPAK1 LOGIN "" "password"\r\n` while Python 3 sends `BJOB1 LOGIN  "password"\r\n` during IMAP login with no username supplied.

The exceptions therefore differed:
$ python -c 'import imaplib; imap = imaplib.IMAP4_SSL("localhost", 993); imap.login("", "password")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/imaplib.py", line 523, in login
    raise self.error(dat[-1])
imaplib.error: [AUTHENTICATIONFAILED] Authentication failed.

$ python3 -c 'import imaplib; imap = imaplib.IMAP4_SSL("localhost", 993); imap.login("", "password")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/imaplib.py", line 597, in login
    typ, dat = self._simple_command('LOGIN', user, self._quote(password))
  File "/usr/lib/python3.7/imaplib.py", line 1199, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.7/imaplib.py", line 1028, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: LOGIN command error: BAD [b'Error in IMAP command received by server.']

→ https://github.com/python/cpython/issues/98241

Workaround: send the quoted data