fixup! fix[ucstest/licence]: Convert to Python 3
Traceback (most recent call last):
  File "80_udm_license", line 546, in <module>
    sys.exit(TestUMC.main())
  File "80_udm_license", line 532, in main
    self.prepare_licenses_for_test()
  File "80_udm_license", line 490, in prepare_licenses_for_test
    self.get_valid_license()
  File "80_udm_license", line 412, in get_valid_license
    license_file=valid_license_file)
  File "/usr/lib/python2.7/dist-packages/univention/testing/license_client.py", line 390, in main
    self.get_the_license(self.order_a_license())
  File "/usr/lib/python2.7/dist-packages/univention/testing/license_client.py", line 243, in get_the_license
    parser = ShopParser(self.log)
  File "/usr/lib/python2.7/dist-packages/univention/testing/license_client.py", line 58, in __init__
    super(ShopParser, self).__init__()
TypeError: super() argument 1 must be type, not classobj

Bug #50631