refactor(ucs-test/10/111): Convert to pytest
Handle case when packages are already installed.

Purge packages after test instead of only removing them.

WARNING:
73_udm-rest/00_general_tests.py::test_all_module_descriptions[test/ip_phone]
fails if the packages are installed:

>     @pytest.mark.parametrize('module', [n for n, m in univention.admin.modules.modules.items() if not getattr(m, 'virtual', False) and 'add' in m.operations])
>     def test_all_module_descriptions(module, udm_client):
>         mod = udm_client.get(module)
> >       mod.new()
> E       AttributeError: 'NoneType' object has no attribute 'new'

Issue univention/ucs#1854