fix(ssh): error handling
split into smaller functions.

extract common code and texts.

Silently ignore SIGPIPE:
> Traceback (most recent call last):
>   File "univention-ssh-askpass", line 152, in <module>
>     print(os.environ[UNIVENTION_SSH_ASKPASS_ENV], end="")
> BrokenPipeError: [Errno 32] Broken pipe

More specific error messages.
> Traceback (most recent call last):
>   File "univention-ssh-askpass", line 278, in <module>
>     print('Failed to read password from %s' % (pw_filename,), file=sys.stderr)
> NameError: name 'pw_filename' is not defined

Simplify closing all FDs.

Convert to Python 3 only code.

Add PEP-484 type hints.

Bug #57115