Bug #28497 ucslint: Fix migrate to dh-python
> Traceback (most recent call last):
>   File "/usr/bin/ucslint", line 51, in <module>
>     import ucslint.base as uub
> ImportError: No module named ucslint.base

Missing dependency on "univention" namespace.