test(recyclebin): workaround to restart listener when activating lastbind
The listener module recyclebin caches the LDAP schema and LDAPs operational attributes for too long.
Therefore after activating the lastbind overlay some transactions get lost.
As a workaround for now, just restart UDL.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/listener/api_adapter.py", line 140, in _handler
    self._module_handler.error_handler(dn, old, new, command, exc_type, exc_value, exc_traceback)
  File "/usr/lib/python3/dist-packages/univention/listener/handler.py", line 218, in error_handler
    raise exc_value.with_traceback(exc_traceback)
  File "/usr/lib/python3/dist-packages/univention/listener/api_adapter.py", line 125, in _handler
    self._module_handler.remove(dn, old)
  File "/usr/lib/univention-directory-listener/system/recyclebin.py", line 107, in remove
    recyclebin_dn = self._move_deleted_object_to_recyclebin(dn, old, object_type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/univention-directory-listener/system/recyclebin.py", line 146, in _move_deleted_object_to_recyclebin
    dn = obj.create(ignore_license=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 610, in create
    dn = self._create(response=response, serverctrls=serverctrls, ignore_license=ignore_license)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1494, in _create
    raise exc[1].with_traceback(exc[2])
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1476, in _create
    self.lo.authz_connection.add(self.dn, al, serverctrls=serverctrls, response=response, ignore_license=ignore_license)
  File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 644, in add
    raise univention.admin.uexceptions.ldapError(_err2str(msg), original_exception=msg)
univention.admin.uexceptions.ldapError: LDAP Error: Constraint violation: authTimestamp: no user modification allowed.

Bug #58887