fix(ad-connector): request.options access with simple_response threaded d ecorator
Internal server error during "/univention/command/adconnector/service".
Request: /univention/command/adconnector/service

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/notifier/threads.py", line 72, in _run
    result = self._function()  # type: Union[BaseException, _T]
  File "/usr/lib/python3/dist-packages/notifier/__init__.py", line 188, in __call__
    return self._function(*tmp, **self._kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/adconnector/__init__.py", line 343, in _run_it
    if request.options.get('action') == 'start':
AttributeError: 'list' object has no attribute 'get'

We should fix Bug #36131, so that simple_response doesn't overwrite request.options with lists anymore.

Bug #43633