test(browser): fix playwright shutdown in case of failures
The page argument was removed.

  File "/usr/share/ucs-test/86_browser/132_miscellaneous_open_all_modules.py", line 63, in test_open_all_modules
    save_trace(page, page.context, module_name, Path('browser').resolve(), ucr, tracing_stop_chunk=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: save_trace() got multiple values for argument 'tracing_stop_chunk'

Bug #57467

Fixes: 5c4c381031d67b7ac0f9b99f1f7088f6f6fdab2c