fix[up] Allow package downgrade on upgrade to UCS-5.0
Upgrade to UCS 5 failes because package downgrades must be allowed
explicitly:
> Die folgenden Pakete werden durch eine ÄLTERE VERSION ERSETZT (Downgrade):
...
> E: Packages were downgraded and -y was used without --allow-downgrades.
> Error: Failed to execute "apt-get -o DPkg::Options::=--force-confold -o DPkg::Options::=--force-overwrite -o DPkg::Options::=--force-overwrite-dir --trivial-only=no --assume-yes --quiet=1 -u dist-upgrade"

Fixes 8e77c84fb38

Bug #51690