Bug #51235: UMC: Add Python 3 compatibility
UMCP is a binary protocol.

Exception ignored in: <bound method MagicBucket.__del__ of <univention.management.console.protocol.server.MagicBucket object at 0x7f9fca341390>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/server.py", line 72, in __del__
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/server.py", line 103, in exit
RuntimeError: dictionary changed size during iteration

File "/usr/lib/python3/dist-packages/notifier/threads.py", line 80, in _run
    result = self._function()
  File "/usr/lib/python3/dist-packages/notifier/__init__.py", line 104, in __call__
    return self._function(*tmp, **self._kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/auth.py", line 109, in __authenticate_thread
    self.pam.authenticate(username, password, **custom_prompts)
  File "/usr/lib/python3/dist-packages/univention/management/console/pam.py", line 226, in authenticate
    if pam_err[1] == PAM_NEW_AUTHTOK_REQD:  # error: ('Authentication token is no longer valid; new one required', 12)
TypeError: 'error' object does not support indexing

fix missing __bool__:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 358, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 261, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 966, in _authentication_finished2
    self.initalize_processor(request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 1008, in initalize_processor
    self.processor.set_credentials(**self.__credentials)
TypeError: set_credentials() argument after ** must be a mapping, not NoneType

Traceback (most recent call last):
  File "/usr/sbin/univention-management-console-server", line 244, in <module>
    umc_daemon.do_action()
  File "/usr/lib/python3/dist-packages/daemon/runner.py", line 267, in do_action
    func(self)
  File "/usr/lib/python3/dist-packages/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/usr/sbin/univention-management-console-server", line 211, in run
    notifier.loop()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 296, in loop
    step()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 251, in step
    if not timer[CALLBACK]():
  File "/usr/lib/python3/dist-packages/notifier/__init__.py", line 104, in __call__
    return self._function(*tmp, **self._kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 578, in _mod_connect
    mod.request(req)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/client.py", line 279, in request
    if self._resend(sock):
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/client.py", line 199, in _resend
    bytessent = sock.send(data)
TypeError: a bytes-like object is required, not 'str'

Decode ACL's:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 358, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 261, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 967, in _authentication_finished2
    self.initalize_processor(request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 1009, in initalize_processor
    self.processor.set_credentials(**self.__credentials)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 173, in set_credentials
    self._reload_acls_and_permitted_commands()
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 177, in _reload_acls_and_permitted_commands
    self._reload_acls()
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 182, in _reload_acls
    self.acls = LDAP_ACLs(self.lo, self._username, ucr['ldap/base'])
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 357, in __init__
    self._read_from_ldap()
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 394, in _read_from_ldap
    self._append(LDAP_ACLs.FROM_GROUP, self.lo.get(value))
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 189, in _append
    command, options = self.__parse_command(command)
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 172, in __parse_command
    if ':' in command:
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 358, in __error_handling
   six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 261, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 967, in _authentication_finished2
    self.initalize_processor(request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 1009, in initalize_processor
    self.processor.set_credentials(**self.__credentials)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 173, in set_credentials
    self._reload_acls_and_permitted_commands()
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 177, in _reload_acls_and_permitted_commands
    self._reload_acls()
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 182, in _reload_acls
    self.acls = LDAP_ACLs(self.lo, self._username, ucr['ldap/base'])
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 358, in __init__
    self._read_from_ldap()
  File "/usr/lib/python3/dist-packages/univention/management/console/acl.py", line 403, in _read_from_ldap
    result.append(g.next())
AttributeError: 'itertools._grouper' object has no attribute 'next'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 358, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 261, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 181, in _response
    return function(self, request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 435, in handle_request_upload
    b64buf = base64.b64encode(buf.read())
  File "/usr/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/server.py", line 202, in _response
    data = bytes(msg)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 331, in __bytes__
    return Message._formattedMessage(self._id, self._type, self.mimetype, self.command, body, self.arguments)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 122, in _formattedMessage
    data = json.dumps(body)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'xxx' is not JSON serializable

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/notifier/threads.py", line 80, in _run
    result = self._function()
  File "/usr/lib/python3/dist-packages/notifier/__init__.py", line 104, in __call__
    return self._function(*tmp, **self._kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/pam.py", line 255, in change_password
    message = self._parse_error_message_from(pam_err.args, prompts)
  File "/usr/lib/python3/dist-packages/univention/management/console/pam.py", line 310, in _parse_error_message_from
    error_message = self._parse_password_change_fail_reason(prompt)
  File "/usr/lib/python3/dist-packages/univention/management/console/pam.py", line 339, in _parse_password_change_fail_reason
    match = pattern.search(prompt)
TypeError: cannot use a bytes pattern on a string-like object