long does not exist in python3
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 236, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 410, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 761, in _doit
    dn = object.create()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 558, in create
    dn = self._create(response=response, serverctrls=serverctrls)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1244, in _create
    al.extend(self._ldap_modlist())
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1724, in _ldap_modlist
    ml = self._modlist_password_expiry(ml, pwhistoryPolicy)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1873, in _modlist_password_expiry
    sambaPwdLastSetValue = '0' if pwd_change_next_login else str(long(time.time()))
NameError: name 'long' is not defined