fix(ucs-test): reading child-fd on timeout
> Traceback (most recent call last):
>   File "ucs-test", line 212, in <module>
>     sys.exit(main())
>   File "ucs-test", line 205, in main
>     return test_set.run_tests(options.filter, options.dry, options.hold)
>   File "ucs-test", line 155, in run_tests
>     test_result.run()
>   File "univention/testing/data.py", line 892, in run
>     self.case.run(self)
>   File "univention/testing/data.py", line 801, in run
>     self._run_tee(proc, result, to_stdout, to_stderr)
>   File "univention/testing/data.py", line 682, in _run_tee
>     stream.close()
> AttributeError: 'NoneType' object has no attribute 'close'

While collecting output fragment `select()` timed out on `next_read` as
there was no additional output to collect. That triggered using the
fallback `list(channels)`, which included `rfd`, which was mapped to
`stream = None`.

Setup `rfd` by providing `stream, out, buf` so it can be handled the
same as `stdout` and `stderr`.

Fixes: 34035f727ad372c1bb64881a7a3fc35056ea1766
Issue univention/ucs#1854