fix(vnc-installation): screenshot directory
Inside the docker container running as user $UID the process running in
directory /test does not have permission to create /screenshots:

> Traceback (most recent call last):
>   File "utils/installation_test/vnc-install-ucs.py", line 45, in <module>
>     main()
>   File "utils/installation_test/vnc-install-ucs.py", line 41, in main
>     inst.installation()
>   File "/test/utils/installation_test/installation.py", line 405, in installation
>     self.screenshot('error.png')
>   File "/test/utils/installation_test/installation.py", line 34, in screenshot
>     os.mkdir(self.args.screenshot_dir)
> OSError: [Errno 13] Permission denied: '../screenshots'

Bug #54636