style: fix ruff issues
management/univention-directory-listener/examples/complex_handler.py:26:32: error[UP008] [*] Use `super()` instead of `super(__class__, self)`
management/univention-directory-manager-modules/modules/univention/udm/encoders.py:313:25: error[UP008] [*] Use `super()` instead of `super(__class__, self)`
management/univention-directory-manager-modules/modules/univention/udm/encoders.py:510:25: error[UP008] [*] Use `super()` instead of `super(__class__, self)`
management/univention-management-console/dev/dh-umc-module-install:113:50: error[F507] `%`-format string has 0 placeholder(s) but 1 substitution(s)
services/univention-ad-connector/univention-adconnector-list-rejected:90:9: error[SIM113] Use `enumerate()` for index variable `i` in `for` loop
services/univention-printserver/univention-lpadmin:108:9: error[SIM113] Use `enumerate()` for index variable `i` in `for` loop
services/univention-s4-connector/univention-s4connector-list-rejected:79:9: error[SIM113] Use `enumerate()` for index variable `i` in `for` loop
test/ucs-test/tests/21_appcenter-uninstall/25_app_uninstall.py:66:24: error[F507] `%`-format string has 0 placeholder(s) but 1 substitution(s)
test/ucs-test/tests/42_authorization/06_default_roles_linux_client_manager_udm_rest.py:48:9: error[S501] Probable use of `requests` call with `verify=False` disabling SSL certificate checks
test/ucs-test/tests/81_keycloak/05_univention-keycloak.py:30:9: error[RUF050] [*] Empty `if` statement

Bug #31771