Bug #34234 ucr: pyflakes
Fix undefined reference to DEFAULTSECT

Fix undefined reference to vars.

Catch more specific exception.

Directly check dict() (instead of list())

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@72648 1b283449-9f2f-0410-b571-8eb228e1a901