Bug #37123: Fix "force printername" modification check
Jenkins regression:
> Traceback (most recent call last):
>   File "42_force_printername", line 124, in <module>
>     test_run(ucr, None)
>   File "42_force_printername", line 116, in test_run
>     close_fds=True)
>   File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1259, in
>   _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

/{usr → etc}/init.d/univention-directory-listener

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-0@57222 1b283449-9f2f-0410-b571-8eb228e1a901