Bug #53111: identifiers should be escaped to prevent parsing errors
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/mail/dovecot_shared_folder.py", line 426, in imap_set_mailbox_acls
    imap.setacl(mailbox, identifier, dovecot_acls[right][0])
  File "/usr/lib/python3.7/imaplib.py", line 764, in setacl
    return self._simple_command('SETACL', mailbox, who, what)
  File "/usr/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.7/imaplib.py", line 1027, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: SETACL command error: BAD [b'Error in IMAP command SETACL: Invalid ACL right: U (0.001 + 0.000 secs).']

If not quoted, the IMAP command is split at space characters.
Therefore, the unescaped group identifier '$Domain Users' caused the
traceback above.
To prevent this issue, the identifier has to be quoted entirely (not
only some parts!).

See also: https://tools.ietf.org/html/rfc3501#section-4.3