Bug #50648: prevent the old broken logic to be applied
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 412, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 750, in _doit
    default_containers = object.get_default_containers(lo)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1688, in get_default_containers
    default_containers = settings_directory.lookup(None, lo, '', required=True)[0]
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1730, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 244, in __init__
    self._validate_superordinate(False)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1001, in _validate_superordinate
    self.superordinate = univention.admin.objects.get_superordinate(self.module, None, self.lo, self.dn or self.position.getDn())
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 79, in get_superordinate
    super_module = set(univention.admin.modules.name(x) for x in univention.admin.modules.identify(dn, attr)) & super_modules
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 665, in identify
    if 'univentionObjectType' in attr and attr['univentionObjectType'] and attr['univentionObjectType'][0].decode('ASCII', 'replace') in modules:
TypeError: 'map' object is not subscriptable