Bug #55184: fix broken env job
I think this might happen because the new primary IP has not been
replicated to the replica

+ univention-register-network-address --verbose
ConnectionError: ('Could not send request.', SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)'))