Revert "Bug #52763: temporary hotfix"
This reverts commit c96a0b75d2f1a62800898d7397fcd8a801766b4f.

3 years later ... this breaks OpenStack:

> AssertionError: ## Check failed: 11_nameserver - Nameserver sind nicht ansprechbar ##   1 der konfigurierten Nameserver anworten nicht auf DNS-Anfragen.   Bitte sicherstellen, dass die DNS-Einstellungen in {setup:network} korrekt konfiguriert sind.   Falls das Problem bestehen bleibt stellen Sie sicher, dass der Nameserver mit dem Netzwerk verbunden ist und die DNS-Forwarder das Internet erreichen können (www.univention.de).      Der Nameserver 192.168.0.3 (UCR Variable 'dns/forwarder1') ist nicht ansprechbar:   Eine Zeitüberschreitung trat beim Erreichen des Nameservers auf (ist er online?). assert False

<https://jenkins2022.knut.univention.de/job/UCS-5.0/job/UCS-5.0-7/job/AutotestJoinOpenstack/lastCompletedBuild/SambaVersion=no-samba,Systemrolle=master/testReport/00_checks/81_diagnostic_checks/test_run_diagnostic_checks_11_nameserver_/>