crudesaml: Update from 1.8 to 1.9
Fix format string vulnerability:
cy2_saml.c: In function 'saml_log':
cy2_saml.c:91:41: error: format not a string literal and no format arguments [-Werror=format-security]
  sasl_utils->log(sasl_utils->conn, pri, msg);
                                         ^~~
cy2_saml.c: In function 'saml_error':
cy2_saml.c:106:44: error: format not a string literal and no format arguments [-Werror=format-security]
  sasl_utils->seterror(sasl_utils->conn, 0, msg);
                                            ^~~

Fix use of private function:
saml.c:389:11: warning: implicit declaration of function 'lasso_provider_verify_saml_signature'; did you mean 'lasso_provider_verify_signature'? [-Wimplicit-function-declaration]
   error = lasso_provider_verify_saml_signature(idp, node, doc);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           lasso_provider_verify_signature

Switch from explicit *-dbg packages to automatic -dbgsym packages.