Bug #54085: fix moving of users/ldap objects
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 344, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 247, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 321, in _response
    result = _multi_response(self, request)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 181, in _response
    return function(self, request)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 443, in _response
    return list(function(self, iterator, *nones))
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 289, in _fake_func
    yield function(self, *args)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/mixins.py", line 158, in progress
    ret = progress_obj.poll()
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/mixins.py", line 102, in poll
    six.reraise(*self.exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 431, in _thread
    for res in function(self, iterator, *nones):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/__init__.py", line 375, in move
    module.move(object, options['container'])
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/udm_ldap.py", line 588, in move
    obj.move(dest)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 805, in move
    res = n(self._move(newdn, ignore_license=ignore_license))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/ldap.py", line 315, in _move
    subelements = self.lo.search(base=self.dn, scope='one', attr=[b'objectClass'])  # FIXME: identify may fail, but users will raise decode-exception
  File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 669, in search
    return self.lo.search(filter, base, scope, attr, unique, required, timeout, sizelimit, serverctrls=serverctrls, response=response)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 208, in _decorated
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 516, in search
    res = self.lo.search_ext_s(base, ldap_scope, filter, attr, serverctrls=serverctrls, clientctrls=None, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1259, in search_ext_s
    return self._apply_method_s(SimpleLDAPObject.search_ext_s,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1197, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 845, in search_ext_s
    msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 841, in search_ext
    timeout,sizelimit,
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
TypeError: ('attrs_from_List(): expected string in list', b'objectClass')