fix(UCR): Handle UCR cache signature as bytes
/var/cache/univention-config/cache caches all `.info` files from
`/etc/univention//registry.info/` using Python pickle, which requires
byte access, but the file starts with a one-line signature which still
uses str. This may lead to the following Traceback:

> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 707, in load
>     version = self._get_cache_version(cache_file)
>   File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 681, in _get_cache_version
>     match = ConfigHandlers.VERSION_RE.match(line)
> TypeError: cannot use a string pattern on a bytes-like object

Convert checking the signature to use bytes.

Bug #55230