Bug #32747: ucs-test: Fix traceback in samba lib
> Traceback (most recent call last):
>   File "35smbclient_auth", line 126, in <module>
>     Test().main()
>   File "35smbclient_auth", line 53, in main
>     wait_for_drs_replication("(sAMAccountName=%s)" % (self.username,), attrs="objectSid")
>   File "/usr/lib/pymodules/python2.6/univention/testing/ucs_samba.py", line 33, in wait_for_drs_replication
>     if res:
> UnboundLocalError: local variable 'res' referenced before assignment

And fix the usual bunch of pylint issues like:
- break long lines.
- remove unused imports.
- prefix unused variables by '_'.
- trailing white space at end of line
- missing withe space around operators
- convert subprocess.Popen().wait() to subprocess.call().

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-3.2-0@44611 1b283449-9f2f-0410-b571-8eb228e1a901