Bug #52045: migrate kpasswd_change_pwd.py to Python 3
Hopefully just fixes:
Traceback (most recent call last):
  File "kpasswd_change_pwd.py", line 45, in <module>
    status = kpasswd.expect([pexpect.TIMEOUT, 'New password for %s@%s:' % (opts.username, ucr['kerberos/realm']), "kpasswd: krb5_get_init_creds: Preauthentication failed", ])
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 339, in expect
    compiled_pattern_list = self.compile_pattern_list(pattern)
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 228, in compile_pattern_list
    p = self._coerce_expect_string(p)
  File "/usr/lib/python2.7/dist-packages/pexpect/spawnbase.py", line 138, in _coerce_expect_string
    return s.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 20: ordinal not in range(128)