Bug #34819 test: Fix logfile traceback
when logfile is not set in any section, the following traceback occurs:

> Traceback (most recent call last):
>   File "./ucs-ec2-create", line 136, in <module>
>     main()
>   File "./ucs-ec2-create", line 88, in main
>     vms.append( univention_ec2_lib.VM_EC2(host, config) )
>   File "/var/lib/jenkins/workspace/Customers/01997_REDACTED/OXIN8 - dev - large env tests/default/python/ec2/lib.py", line 645, in __init__
>     VM.__init__(self, section, config, 'ec2')
>   File "/var/lib/jenkins/workspace/Customers/01997_REDACTED/OXIN8 - dev - large env tests/default/python/ec2/lib.py", line 140, in __init__
>     if self.logfile:
> AttributeError: VM_EC2 instance has no attribute 'logfile'

Initialize logfile to None.
Remove info message about logfile not being set.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-2@62314 1b283449-9f2f-0410-b571-8eb228e1a901