Bug #51235: UMC: Exception.with_traceback() is a method in python3
Therefore we have to rename our (unused) flag.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 198, in _recv
    self.handle(msg)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 269, in handle
    six.reraise(self.__init_etype, self.__init_exc, self.__init_etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
TypeError: 'bool' object is not callable