Bug #52043: decode GUID
* decode GUID
* remove unused GUID arguments

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 2178, in poll
    samba_object = self.__object_from_element(element)
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 1281, in __object_from_element
    olddn = self.encode(self._get_DN_for_GUID(GUID))
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 925, in _get_DN_for_GUID
    return self._decode_dn_from_config_option(self._get_config_option('S4 GUID', self.__encode_GUID(GUID)))
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/__init__.py", line 921, in __encode_GUID
    return base64.b64encode(GUID).decode('ASCII')
AttributeError: 'bytes' object has no attribute 'encode'