fix(pwreset): Move logic into join script
UCRV `ldap/base` is only known *after* join.

Set derived UCRVs only in join script. Only restart local slapd from
join script.

Fix test to use dict[key] instead of dict.get(key) as `None` is not
handles:
> Traceback (most recent call last):
>   File "63univention-admingrp-user-passwordreset.py", line 238, in <module>
>     passwordreset_attributes += ',description'
> TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

Bug #55602, Bug #56099
univention/ucs#1455
univention/ucs!636
Fixes: 76d90c7a8aa1cc19d9e4d1ddee9e76ae25e5f066