Bug #50493: Add missing extend_path in handler namespace packages
Some handler namespace packages were missing "extend_path". This results
in a traceback in case a handler is installed in the old
"/usr/lib/pymodules/python2.7/univention/admin/handlers/" path. One
example is the old cyrus mailquota.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/management/console/protocol/modserver.py", line 103, in _load_module
    self.__module = __import__(file_, [], [], modname)
  File "/usr/lib/pymodules/python2.7/univention/management/console/modules/uvmm/__init__.py", line 45, in <module>
    from univention.management.console.modules.uvmm.profiles import Profiles
  File "/usr/lib/pymodules/python2.7/univention/management/console/modules/uvmm/profiles.py", line 46, in <module>
    univention.admin.modules.update()
  File "/usr/lib/python2.7/dist-packages/univention/admin/modules.py", line 123, in update
    os.path.walk(dir, _walk, p)
  File "/usr/lib/python2.7/posixpath.py", line 239, in walk
    walk(name, func, arg)
  File "/usr/lib/python2.7/posixpath.py", line 231, in walk
    func(arg, top, names)
  File "/usr/lib/python2.7/dist-packages/univention/admin/modules.py", line 108, in _walk
    m = __import__(mod, globals(), locals(), name)
ImportError: No module named mailquota