Bug #25619: Fix traceback in univention-repository-update
Traceback (most recent call last):
  File "/usr/sbin/univention-repository-update", line 278, in <module>
    update_net( options )
  File "/usr/sbin/univention-repository-update", line 204, in update_net
    inst_fd.write( 'VERSION=%d.%d\n' % ( min_version.major, min_version.minor ) )
AttributeError: 'NoneType' object has no attribute 'major'

In some rare cases apt-mirror does not mirror any repositories, in which case
the for loop will not find any version and thus min_version remains unset.

Catch that case and just skip writing the file.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@31119 1b283449-9f2f-0410-b571-8eb228e1a901