Bug #40255 UVMM: Remove unused imports
"libvirt" refuses to be imported by SETUID binaries like the
univention-directory-listener (since 1.1.4 to fix CVE-2013-4400):

> LISTENER    ( ERROR   ) : import of filename=/usr/lib/univention-directory-listener/system/uvmmd-nodes.py failed
> Traceback (most recent call last):
>   File "/usr/lib/univention-directory-listener/system/uvmmd-nodes.py", line 44, in <module>
>     from univention.uvmm.uvmm_ldap import SERVICES, ldap2fqdn
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/uvmm_ldap.py", line 46, in <module>
>     from helpers import TranslatableException, N_ as _, FQDN as HOST_FQDN
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/helpers.py", line 77, in <module>
>     import libvirt
>   File "/usr/lib/pymodules/python2.7/libvirt.py", line 20, in <module>
>     import libvirtmod
> SystemError: dynamic module not initialized properly
> LISTENER    ( ERROR   ) : import of filename=/usr/lib/univention-directory-listener/system/uvmmd-nodes.py failed in module_import()

The import of "libvirt" is quiet useless, as "helper.py" contains an
assorted collection of unrelated functions, which import lots of
libraries. The UVMM listener module just wants one function, but due to
the recursive nature of the import mechanism a lot of modules are
imported, among them libvirt.

Remove the no longer used dictionary to map libvirt error codes to
libvirt error constants, which makes importing "libvirt" obsolete.

Remove the global and unused cloud connection logger, which makes import
"logginf" obsolete".

Backport of r66332 Bug #40133

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-4@66336 1b283449-9f2f-0410-b571-8eb228e1a901