fix(umc-client): show error message instead of traceback on failed authentication in umc-command
This was broken in Bug #55913 git:683888394833c98b1c4cf2a2f83f34bfc4cd8556

Previous output:
$ umc-command -UAdministrator -P univention1 udm/query
23.03.23 11:02:58.935  DEBUG_INIT
error: authentication failed

Bug #43633