fix[ucs-test]: Detect versions: float
> ## versions:
> ##  4.1: skip
leads to
> TypeError: '<=' not supported between instances of 'float' and 'tuple'
as it is parsed by YAML as float().

Check for expected types - hello `pip install enforce`
Convert from float("inf") to sys.maxsize
Add more docstring testing

Bug #53428