fixup! Bug #31771: PEP8
cf9cc3001af29578cfbb7908a3fb1b8a2eb2b948 changed `ed` from a list into a
string which is wrong.
The package has never been released since that.

Problem: Check nameserver entries on DNS zones
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 280, in execute
    result = execute(umc_module, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/20_check_nameservers.py", line 227, in run
    ed.append('')
AttributeError: 'str' object has no attribute 'append'