Bug #50648 python uldap: fix python 3 compatibility for strings
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 412, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 591, in _doit
    lo = univention.admin.uldap.access(host=configRegistry['ldap/master'], port=int(configRegistry.get('ldap/master/port', '7389')), base=baseDN, binddn=binddn, bindpw=pwd, start_tls=tls)
  File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 555, in __init__
    self.lo = univention.uldap.access(host, port, base, binddn, bindpw, start_tls, follow_referral=follow_referral)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 275, in __init__
    self.__open(ca_certfile)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 368, in __open
    self.bind(self.binddn, self.bindpw)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 199, in _decorated
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 295, in bind
    self.lo.simple_bind_s(self.binddn, self.__encode_pwd(self.bindpw))
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 278, in __encode_pwd
    if isinstance(pwd, unicode):
NameError: name 'unicode' is not defined

* prevent the old (broken) logic from Python 2.7 to be applied

Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 412, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 750, in _doit
    default_containers = object.get_default_containers(lo)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1688, in get_default_containers
    default_containers = settings_directory.lookup(None, lo, '', required=True)[0]
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1730, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 244, in __init__
    self._validate_superordinate(False)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1001, in _validate_superordinate
    self.superordinate = univention.admin.objects.get_superordinate(self.module, None, self.lo, self.dn or self.position.getDn())
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 79, in get_superordinate
    super_module = set(univention.admin.modules.name(x) for x in univention.admin.modules.identify(dn, attr)) & super_modules
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 665, in identify
    if 'univentionObjectType' in attr and attr['univentionObjectType'] and attr['univentionObjectType'][0].decode('ASCII', 'replace') in modules:
TypeError: 'map' object is not subscriptable

* replace basestring

* In Python 2: we have to support bytes and unicode
* In Python 3: we have to support bytes
* In Python 3: better catch str/unicode as well instead of handling it as list (?!)

* Make access.__get_new_dn handle bytes in modlist