Bug #50631: add missing dependency
univention/testing/ucs_samba.py:        return subprocess.call('/usr/lib/nagios/plugins/check_univention_replication', **kwargs) == 0
univention/testing/utils.py:            cmd = ('/usr/lib/nagios/plugins/check_univention_replication', '-c', '1')

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/testing/udm.py", line 718, in __exit__
    self.cleanup()
  File "/usr/lib/python2.7/dist-packages/univention/testing/udm.py", line 674, in cleanup
    utils.wait_for_replication(verbose=False)
  File "/usr/lib/python2.7/dist-packages/univention/testing/utils.py", line 484, in wait_for_listener_replication
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory