Bug #50648 UDM handlers: replace iteritems() with items()
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 412, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 986, in _doit
    for object in univention.admin.modules.lookup(module, co, lo, scope='sub', superordinate=superordinate, base=position.getDn(), filter=filter):
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 936, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1730, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1282, in __init__
    univention.admin.handlers.simpleLdap.__init__(self, co, lo, position, dn, superordinate, attributes=attributes)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 241, in __init__
    self.__set_options()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1091, in __set_options
    for opt, option in options.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'