fix(umc-saml): fix SAML identity cache in multiprocessing mode
The identity cache was used by multiple processes. We have to restrict it to use one cache per process.

MAIN        ( WARN    ) : Startup of SAML2.0 service provider failed:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/saml.py", line 214, in reload
    cls.SP = Saml2Client(config_file=cls.configfile, identity_cache=cls.identity_cache, state_cache=shared_memory.saml_state_cache)
  File "/usr/lib/python3/dist-packages/saml2/client_base.py", line 108, in __init__
    self.users = Population(identity_cache)
  File "/usr/lib/python3/dist-packages/saml2/population.py", line 13, in __init__
    self.cache = Cache(cache)
  File "/usr/lib/python3/dist-packages/saml2/cache.py", line 27, in __init__
    self._db = shelve.open(filename, writeback=False, protocol=2)
  File "/usr/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.7/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable

Bug #56303