fix(ucs-test/73/00): Handle error case
UDM HTTP REST API server is *not* restarted when a new UDM module is
installed: It will get picked up by `univention.admin.modules.update()`,
but *not* by the server. Thus the test might fail when
`univention-directory-manager-module-example*` is installed:

73_udm-rest/00_general_tests.py::test_all_module_descriptions[test/ip_phone]

>     @pytest.mark.parametrize('module', [n for n, m in univention.admin.modules.modules.items() if not getattr(m, 'virtual', False) and 'add' in m.operations])
>     def test_all_module_descriptions(module, udm_client):
>         mod = udm_client.get(module)
> >       mod.new()
> E       AttributeError: 'NoneType' object has no attribute 'new'

Issue univention/ucs#1854