Bug #50648 test: Add Python 3 compatibility
* fix TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'
* Fix wrong use of ldap-base
fixes 8666c032e7e73b7b686cd07c7b5a06165e5c4a9e for systems not having
ldap/base == dc=domainname
* migrate ipaddr → ipaddress
* fix 61_udm-users/27_country_names_uptodate
Traceback (most recent call last):
  File "27_country_names_uptodate", line 19, in <module>
    current_countries = sorted([(country.alpha2, country.name) for country in pycountry.countries.objects], key=lambda x: x[0])
AttributeError: 'ExistingCountries' object has no attribute 'objects'
* adjust UDM hooks for python 3 compatibility
* use ldap.initialize() instead of ldap.open()
* Fix 60failedldif
60failedldif: Zeile 17: continue: nur in einer `for', `while' oder `until' Schleife sinnvoll.
* add more debug output to dockertest.py