Bug ##50648:
remove use of deprecated _2utf8()
    Traceback (most recent call last):
      File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 236, in doit
        output = univention.admincli.admin.doit(arglist)
      File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 410, in doit
        out = _doit(arglist)
      File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 844, in _doit
        object = univention.admin.objects.get(module, co, lo, position='', dn=dn)
      File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 108, in get
        obj = univention.admin.modules.lookup(module.module, co, lo, base=dn, superordinate=superordinate, scope='base', unique=True, required=True)[0]
      File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 913, in lookup
        tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
      File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1740, in lookup
        print(filter_str, base, scope, attr, unique, required, timeout, sizelimit, serverctrls, response)
      File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 756, in search
        return self.lo.search(filter, base, scope, attr, unique, required, timeout, sizelimit, serverctrls=serverctrls, response=response)
      File "/usr/lib/python3/dist-packages/univention/uldap.py", line 200, in _decorated
        return func(self, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/univention/uldap.py", line 505, in search
        res = self.lo.search_ext_s(base, ldap_scope, filter, attr, serverctrls=serverctrls, clientctrls=None, timeout=timeout, sizelimit=sizelimit)
      File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1259, in search_ext_s
        return self._apply_method_s(SimpleLDAPObject.search_ext_s,*args,**kwargs)
      File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1197, in _apply_method_s
        return func(self,*args,**kwargs)
      File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 845, in search_ext_s
        msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
      File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 841, in search_ext
        timeout,sizelimit,
      File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 313, in _ldap_call
        result = func(*args,**kwargs)
    TypeError: search_ext() argument 1 must be str, not bytes