Bug #50648 UDM users/user: fix decoding bytes
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 396, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 666, in _doit
    out.extend(cli.modify(input, append, remove, parsed_append_options, parsed_remove_options, parsed_options, policy_reference, policy_dereference))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 695, in modify
    return self._modify(self.module_name, self.module, self.dn, self.lo, self.position, self.superordinate, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 898, in _modify
    dn = object.modify()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1443, in modify
    return super(object, self).modify(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 663, in modify
    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1340, in _modify
    self._ldap_post_modify()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1683, in _ldap_post_modify
    self.__update_groups()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1543, in __update_groups
    self.__rewrite_member_uid(group)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1575, in __rewrite_member_uid
    UIDs = self.lo.getAttr(memberDNstr, 'uid')
  File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 639, in getAttr
    return self.lo.getAttr(dn, attr, required)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 208, in _decorated
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/uldap.py", line 483, in getAttr
    result = self.lo.search_s(dn, ldap.SCOPE_BASE, '(objectClass=*)', [attr])
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 852, in search_s
    return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1259, in search_ext_s
    return self._apply_method_s(SimpleLDAPObject.search_ext_s,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1197, in _apply_method_s
    return func(self,*args,**kwargs)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 845, in search_ext_s
    msgid = self.search_ext(base,scope,filterstr,attrlist,attrsonly,serverctrls,clientctrls,timeout,sizelimit)
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 841, in search_ext
    timeout,sizelimit,
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
 TypeError: search_ext() argument 1 must be str, not bytes