Bug #23527: Remove duplicate argument
> File "/usr/sbin/ucs-test", line 163, in main
>     test_set.run_tests(tests, options.filter, options.dry)
> TypeError: run_tests() takes at most 3 arguments (4 given)

Since test_set is now an instance, there is no need to pass tests any
longer.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@33643 1b283449-9f2f-0410-b571-8eb228e1a901