test(udm-rest): wait for udm-rest fixture reload before restarting udm-rest
00_general_tests.py::test_create_modify_move_remove restarts udm-rest
in the beginning of the test, but the fixture udm_rest (class UDM univention.testing)
already issued a udm-rest reload. The restart of udm-rest breaks the
reload and leads to a nastry traceback

  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/univention/admin/rest/__main__.py", line 132, in run_server
      tornado.ioloop.IOLoop.current().start()
    File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
      self._run_once()
    File "/usr/lib/python3.11/asyncio/base_events.py", line 1884, in _run_once
      event_list = self._selector.select(timeout)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/selectors.py", line 468, in select
      fd_event_list = self._selector.poll(timeout, max_ev)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3/dist-packages/univention/admin/rest/__main__.py", line 190, in signal_handler_reload
      for pid in shared_memory.children.values():
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 2, in values
    File "/usr/lib/python3.11/multiprocessing/managers.py", line 821, in _callmethod
      conn.send((self._id, methodname, args, kwds))
    File "/usr/lib/python3.11/multiprocessing/connection.py", line 205, in send
      self._send_bytes(_ForkingPickler.dumps(obj))
    File "/usr/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
      self._send(header + buf)
    File "/usr/lib/python3.11/multiprocessing/connection.py", line 367, in _send
      n = write(self._handle, buf)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  BrokenPipeError: [Errno 32] Broken pipe

Avoid that by "waiting" for the restart

Bug #50253
Issue univention/dev/ucs#3296