Bug #50648 UDM handlers: reduce()
use functools.reduce() instead of deprecated reduce()

Traceback (most recent call last):
  File "./management/univention-directory-manager-modules/univention-cli-server", line 236, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 410, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 909, in _doit
    dn = object.modify()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1437, in modify
    return super(object, self).modify(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 651, in modify
    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1325, in _modify
    ml = self._ldap_object_classes(ml)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1408, in _ldap_object_classes
    unneeded_ocs |= reduce(set.union, (set(module_options[option].objectClasses) for option in removed_options), set())
NameError: name \'reduce\' is not defined