s4c: workaround changed type
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 1486, in sync_to_ucs
    post_ucs_modify_function(self, property_type, object)
  File "/usr/lib/python3/dist-packages/univention/s4connector/s4/ntsecurity_descriptor.py", line 137, in ntsd_to_ucs
    s4connector._remember_entryCSN_commited_by_connector(entryUUID, entryCSN)
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 621, in _remember_entryCSN_commited_by_connector
    entryCSN_set = set(value.split(','))
                       ^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'