Bug #50648 UDM shares/printer: do not use default model=None
self['model'] may be None, which resulted previously in a wrong default value of "cn=misc,cn=cups,cn=univention,..."

Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 735, in _doit
    object.open()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/shares/printer.py", line 239, in open
    models = univention.admin.modules.get('settings/printermodel').lookup(None, self.lo, filter_format('printerModel="%s*', [self['model']]))
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in filter_format
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in <genexpr>
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 41, in escape_filter_chars
    s = assertion_value.replace('\\', r'\5c')
AttributeError: 'NoneType' object has no attribute 'replace'