Bug #54968: restrict check execution to valid system roles
e.g. causes:
Traceback (most recent call last):
  File "/usr/share/univention-monitoring-client/scripts//check_univention_ldap", line 54, in <module>
    LDAP.main()
  File "/usr/lib/python3/dist-packages/univention/monitoring/__init__.py", line 74, in main
    self.write_metrics()
  File "/usr/share/univention-monitoring-client/scripts//check_univention_ldap", line 40, in write_metrics
    slapd_port = ucr['slapd/port'].split(',')[0]
AttributeError: 'NoneType' object has no attribute 'split'
run-parts: /usr/share/univention-monitoring-client/scripts//check_univention_ldap exited with return code 1
mdb_env_open failed, error 2 No such file or directory