Bug #50648: use six.string_types instead of bytestring
Traceback (most recent call last):
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 223, in doit
    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 412, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 999, in _doit
    if s.tostring(v):
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 410, in tostring
    if isinstance(self.delimiter, basestring):
NameError: name 'basestring' is not defined