test[univention-translog]: XFail bugs
SambaVersion=s4,Systemrolle=master
- 25_directory-notifier.01_univention_translog_tool.test_translog_check_silent[check]

> # …/univention-translog check
> ERROR:/var/lib/univention-ldap/notify/transaction:926:'926 dc=autotest071,dc=local m\n': Foreign dn
                                                                ^    ^
> # ucr get ldap/base
> dc=AutoTest071,dc=local
     ^   ^
fails because the LDAP base is not consistent:

SambaVersion=no-samba,Systemrolle=backup
- 25_directory-notifier.01_univention_translog_tool.test_translog_check[lookup 1]

> WARNING:Transaction 1 is invalid
> Traceback (most recent call last):
>   File "…/univention-translog", line 1444, in <module>
>     exit(main())
>   File "…/univention-translog", line 424, in main
>     return opt.func(opt) or 0
>   File "…/univention-translog", line 608, in lookup
>     print(translog[tid])
>   File "…/univention-translog", line 330, in __getitem__
>     self.seek(tid)
>   File "…/univention-translog", line 365, in seek
>     raise IndexError(tid)
> IndexError: 1

- 25_directory-notifier.01_univention_translog_tool.test_translog_check_silent[-n -l load 1]

> AssertionError: assert '/usr/share/u... is invalid\n' == ''
>   -   self.log.warn("Transaction %d is invalid", tid)
>   - 2021-12-06 02:46:12,102:WARNING:Transaction 1 is invalid

- 25_directory-notifier.01_univention_translog_tool.test_translog_check_silent[-n -l import -m 1 -M 1]

> WARNING:Transaction 1 is invalid
> Traceback (most recent call last):
>   File "…/univention-translog", line 1444, in <module>
>     exit(main())
>   File "…/univention-translog", line 424, in main
>     return opt.func(opt) or 0
>   File "…/univention-translog", line 498, in import_all
>     translog.seek(start)
>   File "…/univention-translog", line 365, in seek
>     raise IndexError(tid)
> IndexError: 1

Bug #53355