Bug #33101 ucr: Fix UCR dict contract
Use collections.MutableMapping instead of dict(), as the first will mix
in all missing methods.

This results in the following ABI change - all caused by previously
unimplemented methods for which new tests have been added:

$ python tests/test_backend.py
F...F......................F.F....EE......F....
======================================================================
ERROR: test_pop (__main__.TestConfigRegistry)
Test set ucr.pop(key).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_backend.py", line 176, in test_pop
    self.assertEqual(ucr.pop('foo'), 'bar')
KeyError: 'foo'

======================================================================
ERROR: test_popitem (__main__.TestConfigRegistry)
Test set ucr.popitem().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_backend.py", line 182, in test_popitem
    self.assertEqual(ucr.popitem(), ('foo', 'bar'))
KeyError: 'popitem(): dictionary is empty'

======================================================================
FAIL: test_clear (__main__.TestConfigRegistry)
Test set ucr.clear().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_backend.py", line 266, in test_clear
    self.assertIsNone(ucr.get('baz', getscope=True))
AssertionError: (0, 'NORMAL') is not None

======================================================================
FAIL: test_dict (__main__.TestConfigRegistry)
Test merged items.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_backend.py", line 209, in test_dict
    dict([('foo', 'FORCED'), ('bar', 'FORCED'), ('baz', 'NORMAL')])
AssertionError: {} != {'baz': 'NORMAL', 'foo': 'FORCED', 'bar': 'FORCED'}
- {}
+ {'bar': 'FORCED', 'baz': 'NORMAL', 'foo': 'FORCED'}

======================================================================
FAIL: test_iteritems (__main__.TestConfigRegistry)
Test merged items.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_backend.py", line 225, in test_iteritems
    sorted([('foo', 'FORCED'), ('bar', 'FORCED'), ('baz', 'NORMAL')])
AssertionError: Lists differ: [] != [('bar', 'FORCED'), ('baz', 'N...

Second list contains 3 additional elements.
First extra element 0:
('bar', 'FORCED')

- []
+ [('bar', 'FORCED'), ('baz', 'NORMAL'), ('foo', 'FORCED')]

======================================================================
FAIL: test_itervalues (__main__.TestConfigRegistry)
Test merged items.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_backend.py", line 257, in test_itervalues
    sorted(['FORCED', 'FORCED', 'NORMAL'])
AssertionError: Lists differ: [] != ['FORCED', 'FORCED', 'NORMAL']

Second list contains 3 additional elements.
First extra element 0:
FORCED

- []
+ ['FORCED', 'FORCED', 'NORMAL']

======================================================================
FAIL: test_setdefault (__main__.TestConfigRegistry)
Test set ucr.setdefault().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_backend.py", line 188, in test_setdefault
    self.assertEqual(ucr['foo'], 'bar')
AssertionError: None != 'bar'

----------------------------------------------------------------------
Ran 47 tests in 2.117s

FAILED (failures=5, errors=2)

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.2/ucs-4.2-0@76603 1b283449-9f2f-0410-b571-8eb228e1a901