squash! Bug #52043: specify the encoding of the Samba LDAP attributes
Also decode value of con_other_attribute.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 1430, in sync_to_ucs
    result = self.modify_in_ucs(property_type, object, module, position)
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 1170, in modify_in_ucs
    self.__set_values(property_type, object, ucs_object)
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 1129, in __set_values
    set_values(post_attributes)
  File "/usr/lib/python3/dist-packages/univention/s4connector/__init__.py", line 1081, in set_values
    ucs_object[ucs_key] = object['attributes'].get(attributes.con_other_attribute)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 418, in __setitem__
    p = s.parse(v)
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 224, in parse
    if text is None or self.regex is None or self.regex.match(text) is not None:
TypeError: cannot use a string pattern on a bytes-like object