fix(udm users/self): fix inheritance errors after reloading python modules
users/self inherits from users/user.
modules.init('users/user', force_reload=True) reloads the python module, which causes
that users/self still has a reference to the old users/user object
instance leading to:

Traceback (most recent call last):
  File "repr.py", line 8, in <module>
    univention.admin.modules.get('users/self').object(None, lo, None, 'uid=Administrator,cn=users,l=school,l=dev')
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1124, in __init__
    univention.admin.handlers.simpleLdap.__init__(self, co, lo, position, dn, superordinate, attributes=attributes)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 221, in __init__
    attr = self._ldap_attributes()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 2046, in _ldap_attributes
    return super(object, cls)._ldap_attributes() + ['pwdAccountLockedTime']
TypeError: super(type, obj): obj must be an instance or subtype of type

This doesn't happen with Python 3 `super()` call without arguments. When
we drop Python 2 support we should revert the change and adjust all
super calls.

Reproducer:
curl -H 'Accept: application/json' http://Administrator:univention@localhost/univention/udm/users/user/add > /dev/null

curl -H 'Accept: application/json' http://Administrator:univention@localhost/univention/udm/users/self/uid=Administrator,cn=users,l=school,l=dev | python -m json.tool

Reproducer:
> import univention.admin.uldap
> lo,po=univention.admin.uldap.getMachineConnection()
> univention.admin.modules.init(lo, po, univention.admin.modules.get('users/user'), force_reload=True)
> univention.admin.modules.get('users/self').object(None, lo, None, 'uid=Administrator,cn=users,l=school,l=dev')

Bug #55430