Bug #49129 ucr: mypy: Add missing type check
> python/univention/config_registry/handler.py:1044: error: "ConfigHandler" has no attribute "uninstall_divert"