DRPOME: I just want to start the tests ....
Bug #56005

Even disabling selinux via config is not sufficient. You'd need a reboot for the
other packages to notice. Because the file selinux/config exists at all, packages
start to behave weirdly because they are missing policy files and so on.
I'll think about a real solution but I want the tests to start again

Errors ecountered:
Setting up slapd (2.5.13+dfsg-5A~5.2.0.202304212307) ...
  Creating new user openldap... chfn: Permission denied.
adduser: `/bin/chfn -f OpenLDAP Server Account openldap' returned error code 1. Exiting.
dpkg: error processing package slapd (--configure):

failed to get security context of /tmp/slapadd.WVZXi8: No data availablesed: warning: failed to get security context of /tmp/slapadd.WVZXi8: No data availabledone.
error: ssh_selinux_getctxbyname: Failed to get default SELinux security context for root
error: ssh_selinux_setup_pty: getfilecon: Operation not supported
error: ssh_selinux_getctxbyname: Failed to get default SELinux security context for root