fixup! Bug #51330: Migrated Join UMC module to python 3
Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/notifier/threads.py", line 80, in _run
    result = self._function()
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/join/__init__.py", line 431, in _thread
    critical_handler=self.progress_state.critical_handler,
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/join/__init__.py", line 164, in system_join
    passwordFile.write(password)
  File "/usr/lib/python3.7/tempfile.py", line 620, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'