fix(udm): fix removal of non-lowercase group members in fast_member_remove()
`memberUid` is case sensitive in contrast to `uniqueMember`.
A LDAP remove operation must therefor happen with the correct case.
The lowered set put always the lowercase variant into the the remove list.
As we retrieved the current set values directly before this operation we
can use the original case.

01.12.2021 06:25:09.593 LDAP        (PROCESS): sync to ucs: Resync rejected dn: CN=Remoteuser,OU=Standard,OU=Gruppen,OU=SUB,DC=schein,DC=me
01.12.2021 06:25:09.673 LDAP        (PROCESS): sync to ucs:   [         group] [    modify] cn=remoteuser,ou=standard,ou=gruppen,ou=sub,dc=schein,dc=me
01.12.2021 06:25:10.925 LDAP        (ERROR  ): Unknown Exception during sync_to_ucs
01.12.2021 06:25:11.017 LDAP        (ERROR  ): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/connector/__init__.py", line 1374, in sync_to_ucs
    f(self, property_type, object)
  File "/usr/lib/python2.7/dist-packages/univention/connector/ad/__init__.py", line 187, in group_members_sync_to_ucs
    return connector.group_members_sync_to_ucs(key, object)
  File "/usr/lib/python2.7/dist-packages/univention/connector/ad/__init__.py", line 2189, in group_members_sync_to_ucs
    ucs_admin_object.fast_member_remove(uniqueMember_del, memberUid_del, ignore_license=1)
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/groups/group.py", line 418, in fast_member_remove
    return self.lo.modify(self.dn, ml, ignore_license=ignore_license)
  File "/usr/lib/python2.7/dist-packages/univention/admin/uldap.py", line 902, in modify
    raise univention.admin.uexceptions.ldapError(_err2str(msg), original_exception=msg)
ldapError: No such attribute: modify/delete: memberUid: no such value

Fixes: db0d44f0ef5a56542293538c641e4de50d07f6de

Bug #54183