Bug #50648 UDM policies/registry: Make python3 compatible
python3 /usr/lib/python3/dist-packages/univention/admincli/admin.py policies/registry list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 1129, in <module>
    print('\n'.join(doit(sys.argv)))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 983, in _doit
    for object in univention.admin.modules.lookup(module, co, lo, scope='sub', superordinate=superordinate, base=position.getDn(), filter=filter):
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 934, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1751, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 3410, in __init__
    simpleLdap.__init__(self, co, lo, position, dn, superordinate, attributes)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 236, in __init__
    oldinfo = self._post_unmap(oldinfo, self.oldattr)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/policies/registry.py", line 124, in _post_unmap
    key_name = key.split('univentionRegistry;entry-hex-', 1)[1].decode('hex')
AttributeError: 'str' object has no attribute 'decode'