Ensure type is str
  File "/usr/share/univention-directory-manager-tools/univention-cli-server", line 236, in doit\n    output = univention.admincli.admin.doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 410, in doit\n    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 761, in _doit\n    dn = object.create()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 558, in create\n    dn = self._create(response=response, serverctrls=serverctrls)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1233, in _create\n    self._ldap_pre_create()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1609, in _ldap_pre_create\n    univention.admin.allocators.acquireUnique(self.lo, self.position, \'uidNumber\', self[\'uidNumber\'], \'uidNumber\', scope=\'base\')
  File "/usr/lib/python3/dist-packages/univention/admin/allocators.py", line 187, in acquireUnique\n    if not lo.searchDn(base=searchBase, filter=filter_format(\'%s=%s\', (attr, value))):
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in filter_format\n    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 57, in <genexpr>\n    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
  File "/usr/lib/python3/dist-packages/ldap/filter.py", line 41, in escape_filter_chars\n    s = assertion_value.replace(\'\\\\\', r\'\\5c\')
TypeError: a bytes-like object is required, not 'str'