Bug #49129: Fix setting or UCR variables
$ python3 $(which ucr) --debug set apache2/startsite=univention/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 573, in load
    self._handlers = pickler.load()
TypeError: a bytes-like object is required, not 'str'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/ucr", line 65, in <module>
    ub.main(convertToUtf8(sys.argv[1:]))
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 687, in main
    handler_func(args, cmd_opts)
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 241, in handler_commit
    handlers.load()
  File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 586, in load
    self.update()
  File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 759, in update
    self._save_cache()
  File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 804, in _save_cache
    pickler.dump(self._handlers)
TypeError: write() argument must be str, not bytes

Solution: open pickle files with 'rb' / 'wb'

Traceback (most recent call last):
  File "/usr/sbin/ucr", line 65, in <module>
    ub.main(convertToUtf8(sys.argv[1:]))
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 687, in main
    handler_func(args, cmd_opts)
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 160, in handler_set
    changed = ucr.update(changes)
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 256, in update
    for key, value in changes.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

Traceback (most recent call last):
  File "/usr/sbin/ucr", line 65, in <module>
    ub.main(convertToUtf8(sys.argv[1:]))
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 687, in main
    handler_func(args, cmd_opts)
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 160, in handler_set
    changed = ucr.update(changes)
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 264, in update
    registry[key] = value
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 410, in __setitem__
    key.decode('UTF-8')  # only accept valid UTF-8 encoded bytes
AttributeError: 'str' object has no attribute 'decode'

Traceback (most recent call last):
  File "/usr/sbin/ucr", line 65, in <module>
    ub.main(convertToUtf8(sys.argv[1:]))
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 687, in main
    handler_func(args, cmd_opts)
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 163, in handler_set
    None if quiet else 'W: %s is overridden by scope "%s"')
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 195, in _run_changed
    for key, (old_value, new_value) in changed.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

Traceback (most recent call last):
  File "/usr/sbin/ucr", line 65, in <module>
    ub.main(convertToUtf8(sys.argv[1:]))
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 687, in main
    handler_func(args, cmd_opts)
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 163, in handler_set
    None if quiet else 'W: %s is overridden by scope "%s"')
  File "/usr/lib/python3/dist-packages/univention/config_registry/frontend.py", line 204, in _run_changed
    handlers(changed.keys(), (ucr, changed))
  File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 882, in __call__
    handler(arg)
  File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 423, in __call__
    to_fp.write(run_filter(from_fp.read(), ucr, srcfiles=[self.from_file], opts=filter_opts))
  File "/usr/lib/python3/dist-packages/univention/config_registry/handler.py", line 119, in run_filter
    ''' % template[start.end():end.start()])[0]
  File "/usr/lib/python3.5/subprocess.py", line 801, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1431, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'