Bug #52043 S4C: adapt to python 3 strings changes in UDM
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/s4/__init__.py", line 2111, in resync_rejected
    mapped_object = self._object_mapping(property_key, samba_object)
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/__init__.py", line 1838, in _object_mapping
    object = function(self, object, dn_mapping_stored, isUCSobject=(object_type == 'ucs'))
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/s4/__init__.py", line 459, in group_dn_mapping
    return samaccountname_dn_mapping(s4connector, given_object, dn_mapping_stored, isUCSobject, 'group', u'cn', u'posixGroup', 'cn', u'group')
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/s4/__init__.py", line 339, in samaccountname_dn_mapping
    value = unicode(fst_rdn_value_utf8, 'utf8')
TypeError: decoding Unicode is not supported

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/__init__.py", line 1047, in resync_rejected_ucs
    if self.__sync_file_from_ucs(filename, append_error=' rejected'):
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/__init__.py", line 887, in __sync_file_from_ucs
    mapped_object = self._object_mapping(key, object, 'ucs')
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/__init__.py", line 1838, in _object_mapping
    object = function(self, object, dn_mapping_stored, isUCSobject=(object_type == 'ucs'))
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/s4/dns.py", line 247, in dns_dn_mapping
    s4_soa_object = dns_dn_mapping(s4connector, fake_ol_zone_object, dn_mapping_stored, isUCSobject)
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/s4/dns.py", line 295, in dns_dn_mapping
    zone_dn = unicode(ldap.dn.dn2str([zone_rdn] + str2dn(default_dn)), 'utf8')
TypeError: decoding Unicode is not supported