ci[ucslint]: Switch from easy_install to pip3
easy_install no longer works because pypi.org deprecated the old XMLRPC
based API and easy_install does not support the new API.

> Step 5/7 : RUN easy_install3 junit-xml
> Searching for junit-xml
> Reading https://pypi.python.org/simple/junit-xml/
> Scanning index of all packages (this may take a while)
> Reading https://pypi.python.org/simple/
> Couldn't find index page for 'junit-xml' (maybe misspelled?)
> No local packages or working download links found for junit-xml
> error: Could not find suitable distribution for Requirement.parse('junit-xml')
> The command '/bin/sh -c easy_install3 junit-xml' returned a non-zero code: 1

Bug #51546