test(grep-traceback): ignore errors during decoding of logfiles as UTF-8
The listener logs binary data for univention.debug ALL (4) level.
This caused all grep-traceback test to fail:

Traceback (most recent call last):
  File "/usr/share/ucs-test/99_end/01_var_log_tracebacks.py", line 45, in test_var_log_tracebacks
    if not grep_traceback.main(glob.glob('/var/log/univention/*.log'), ignore_exceptions=grep_traceback.COMMON_EXCEPTIONS):
  File "/usr/share/ucs-test/99_end/grep_traceback.py", line 86, in main
    line = _readline(fd)
  File "/usr/share/ucs-test/99_end/grep_traceback.py", line 74, in _readline
    line = fd.readline()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 7583: invalid start byte

The reason why the loglevel was changed to DEBUG will be fixed in a different commit.

Bug #56970