fix(test/update-from-2.4): SA update v2
`sa-update` was never executed in the template, so SpamAssassin does not
yet have any rules. Without a rule-set it does not start and actually
`spamassassin.service` is not running.

During to update to 5.0-0 `spamassassin.postinst` is invoked, which
contains this code block:

> if [ "$1" = "configure" ] && [ -n "$2" ]; then
>     if deb-systemd-helper was-enabled spamassassin.service > /dev/null 2>&1; then
>         invoke-rc.d spamassassin restart
>     fi
> fi

For some (yet) unknown reason `deb-systemd-helper was-enabled` should
prevent the restart, but does not. `journalctl -u spamassassin.service`
reports this:

> config: no rules were found! Do you need to run 'sa-update'?

Updating or fetching the sa-rules failed for several reasons:

1. https://spamassassin.apache.org/ is secured by Let's encrypt and
   their previous chain-of-trust is invald as the "DST X3" root CA
   certificate expired.
   This is fixed by removing that CA.

2. The SA PGP key used to sign the rules has expired and needs to be
   updated before `sa-update` can be used again:

> stdout: DNS TXT query: 2.4.3.updates.spamassassin.org -> 1908044
>  Update available for channel updates.spamassassin.org: -1 -> 1908044
>  DNS A query: sa-update.razx.cloud -> 104.21.69.80, 172.67.206.130
>  fetching https://sa-update.razx.cloud/1908044.tar.gz
>  http: (curl) GET https://sa-update.razx.cloud/1908044.tar.gz, success
>  fetching https://sa-update.razx.cloud/1908044.tar.gz.sha512
>  http: (curl) GET https://sa-update.razx.cloud/1908044.tar.gz.sha512, success
>  fetching https://sa-update.razx.cloud/1908044.tar.gz.sha256
>  http: (curl) GET https://sa-update.razx.cloud/1908044.tar.gz.sha256, success
>  fetching https://sa-update.razx.cloud/1908044.tar.gz.asc
>  http: (curl) GET https://sa-update.razx.cloud/1908044.tar.gz.asc, success
>  Update failed, exiting with code 4
> stderr: gpg: failed to create temporary file '/etc/spamassassin/sa-update-keys/.#lk0x000055dcbba0cf90.master.24499': Keine Berechtigung
>  gpg: Schlüsselblockhilfsmittel`/etc/spamassassin/sa-update-keys/pubring.kbx': Keine Berechtigung
>  gpg: kein schreibbarer Schlüsselbund gefunden: Nicht gefunden
>  gpg: Fehler beim Lesen von `/usr/share/spamassassin/sa-update-pubkey.txt': Allgemeiner Fehler
>  gpg: import from '/usr/share/spamassassin/sa-update-pubkey.txt' failed: Allgemeiner Fehler
>  gpg: process '/usr/bin/gpg --homedir='/etc/spamassassin/sa-update-keys' --batch --no-tty --status-fd=1 -q --logger-fd=1 --import' finished: exit 2
>  gpg: WARNUNG: Unsicheres Besitzverhältnis des Home-Verzeichnis `/etc/spamassassin/sa-update-keys'
>  gpg: process '/usr/bin/gpg' finished: exit 2
>  error: GPG validation failed!
>  The update downloaded successfully, but it was not signed with a trusted GPG
>  key.  Instead, it was signed with the following keys:
>
>      24F434CE
>
>  Perhaps you need to import the channel's GPG key?  For example:
>
>      wget http://spamassassin.apache.org/updates/GPG.KEY
>      sa-update --import GPG.KEY
>
>  channel: GPG validation failed, channel failed

3. By invoking `sa-update` as user `root` several files are then owned
   by that user. Later calls (via cron) by user `debian-spamd` then
   fail.
   Fix file ownership to `debian-spamd`.

Bug #53751