Bug #53102: users/user: cleanup move() logic
* use self._ldap_dn() instead of code duplicate the code to generate a
  (possibly wrong) new LDAP DN
* use self.move() instead of self._move() so that some necessary checks
  if moving is possible are done
* fix moving of objects with more than one child objects, otherwise we
  would get a KeyError:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 1080, in <module>
    print('\n'.join(doit(sys.argv)))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 380, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 651, in _doit
    out.extend(cli.modify(input, append, remove, parsed_append_options, parsed_remove_options, parsed_options, policy_reference, policy_dereference, ignore_not_exists=ignore_not_exists))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 680, in modify
    return self._modify(self.module_name, self.module, self.dn, self.lo, self.position, self.superordinate, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 886, in _modify
    dn = object.modify()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1420, in modify
    return super(object, self).modify(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 636, in modify
    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1322, in _modify
    self._ldap_pre_modify()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1675, in _ldap_pre_modify
    self.move(self._ldap_dn())
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 805, in move
    res = n(self._move(newdn, ignore_license=ignore_license))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 2134, in _move
    subelements = [(moved[subdn], subattrs) for (subdn, subattrs) in subelements]
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 2134, in <listcomp>
    subelements = [(moved[subdn], subattrs) for (subdn, subattrs) in subelements]
KeyError: 'cn=cn2,uid=baaar,cn=lehrer,cn=users,ou=oldschool,l=school,l=dev'