fix(udm): be robust for invalid data
The syntax class for `univentionBirthday` doesn't permit non-ISO 8601
data, but if they are set in LDAP, certain things break:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 233, in _run
    result: BaseException | _T = self._function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/__init__.py", line 638, in query
    result.extend(module.search(container, objectProperty, objectPropertyValue, superordinate, scope=scope, hidden=hidden, allow_asterisks=USE_ASTERISKS) or [])
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/udm_ldap.py", line 705, in search
    UDM_Error(e).reraise()
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/udm_ldap.py", line 350, in reraise
    raise self.with_traceback(self.exc_info[2])
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/udm_ldap.py", line 688, in search
    result = self.module.lookup(None, ldap_connection, filter_s, base=container, superordinate=superordinate, scope=scope, sizelimit=sizelimit, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 2162, in lookup
    result = lo.filter_lookup_results(result, {'module': cls.module, 'filter': filter_str, 'base': base or cls.ldap_base, 'scope': scope, 'attr': attr})
  File "/usr/lib/python3/dist-packages/univention/admin/uldap.py", line 750, in filter_lookup_results
    return self.authz.filter_search_results(self, results, context=context)
  File "/usr/lib/python3/dist-packages/univention/admin/authorization/__init__.py", line 217, in filter_search_results
    targets = [
  File "/usr/lib/python3/dist-packages/univention/admin/authorization/__init__.py", line 218, in <listcomp>
    self._get_targets(lo, None, target_obj)
  File "/usr/lib/python3/dist-packages/univention/admin/authorization/__init__.py", line 463, in _get_targets
    'new_target': self._get_target(new_target) if new_target is not None else self._empty_target(),
  File "/usr/lib/python3/dist-packages/univention/admin/authorization/__init__.py", line 495, in _get_target
    'attributes': self._get_representation(obj, old),
  File "/usr/lib/python3/dist-packages/univention/admin/authorization/__init__.py", line 529, in _get_representation
    'properties': self._decode_properties(obj, obj.oldinfo) if old else self._decode_properties(obj, obj.info),
  File "/usr/lib/python3/dist-packages/univention/admin/authorization/__init__.py", line 536, in _decode_properties
    return {
  File "/usr/lib/python3/dist-packages/univention/admin/authorization/__init__.py", line 537, in <dictcomp>
    key: univention.admin.types.TypeHint.detect(obj.descriptions[key], key).decode_json(value)
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 101, in decode_json
    return self.to_json_type(self.decode(value))
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 83, in decode
    return self.decode_value(value)
  File "/usr/lib/python3/dist-packages/univention/admin/types.py", line 388, in decode_value
    return self.syntax.to_datetime(value)
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 2906, in to_datetime
    value = cls.parse(value)
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 344, in parse
    raise univention.admin.uexceptions.valueError(self.error_message)
univention.management.console.modules.udm.udm_ldap.UDM_Error: Das eingegebene Datum entspricht nicht ISO 8601, Beispiel: "2009-01-01".

Bug #59560

Issue: univention/dev/internal/dev-issues/dev-incidents#222