Bug #50648: Catch univention.password.CheckFailed in check_cracklib.py
Regression from dea9b6d3841
Error: external program failed: Traceback (most recent call last):   File "/usr/share/univention-heimdal/check_cracklib.py", line 74, in <module>     main()   File "/usr/share/univention-heimdal/check_cracklib.py", line 67, in main     pwdCheck.check(params['new-password'])   File "/usr/lib/python3/dist-packages/univention/password.py", line 143, in check     raise CheckFailed('Password does not meet the password complexity requirements.') univention.password.CheckFailed: Password does not meet the password complexity requirements.