Bug #51062 replication: Fix exception handling
python-ldap raises ldap.LDAPError where ex.args is
- a 2-tuple (errno, msg)
- a 1-tuple (dict(errnum=…),)
- a 1-tuple (dict(desc=…, matched=…, info=…, errno=…),)
- a 0-tuple ()

replication.log_ldap() only handled the second 1-tuple case correctly,
the other cases lead to the handler crashing with:

> Traceback (most recent call last):
>   File "/usr/lib/univention-directory-listener/system/replication.py", line 946, in handler
>     except ldap.LDAPError as ex:
>       log_ldap(ud.ERROR, 'Error', ex, dn=dn)
>   File "/usr/lib/univention-directory-listener/system/replication.py", line 957, in log_ldap
>     ud.debug(ud.LISTENER, severity, 'replication: %s%s: %s' % (ex[0]['desc'], '; dn="%s"' % (dn,) if dn else '', msg))
> IndexError: tuple index out of range

UDL then just continues with the next handler and transaction, which
leads to the current transaction not being replicated to the local LDAP
server in all cases: `replication.py` would either switch to
`failed.ldif` mode or retry depending on UCRV
`ldap/replication/fallback`, but in this case just returns to UDL.

1. Make sure to extract and print useful information from the exception
in all cases.

2. Use `ex.agrs[...]` instead of `args[...]` as the later is no longer
supported with Python 3.

Cherry-pick: a7a0c790d44c227a87ff7c421bd8c27aecbfe32b Bug #51061