Bug #55921: workaround problem with lockfile name
waf somewhen changed the name of the lockfile from ".lock-waf" to
".lock-wscript". Since the "configure" detects a wrong build path:
Setting top to                           : /builds/univention/ucs/services/univention-ldb-modules
Setting out to                           : /builds/univention/ucs/services/univention-ldb-modules/.lock-wscript

Traceback (most recent call last):
  File "/builds/univention/ucs/services/univention-ldb-modules/third_party/waf/waflib/Scripting.py", line 159, in waf_entry_point
    run_commands()
  File "/builds/univention/ucs/services/univention-ldb-modules/third_party/waf/waflib/Scripting.py", line 255, in run_commands
    ctx = run_command(cmd_name)
  File "/builds/univention/ucs/services/univention-ldb-modules/third_party/waf/waflib/Scripting.py", line 239, in run_command
    ctx.execute()
  File "/builds/univention/ucs/services/univention-ldb-modules/third_party/waf/waflib/Configure.py", line 186, in execute
    env.store(os.path.join(Context.run_dir, Options.lockfile))
  File "/builds/univention/ucs/services/univention-ldb-modules/third_party/waf/waflib/ConfigSet.py", line 305, in store
    Utils.writef(filename, ''.join(buf))
  File "/builds/univention/ucs/services/univention-ldb-modules/third_party/waf/waflib/Utils.py", line 270, in writef
    with open(fname, m) as f:
IsADirectoryError: [Errno 21] Is a directory: '/builds/univention/ucs/services/univention-ldb-modules/.lock-wscript'

Starting point to fix it upstream:

diff --git a/services/univention-ldb-modules/third_party/waf/waflib/Configure.py b/services/univention-ldb-modules/third_party/waf/waflib/Configure.py
index 5762eb6695..5fe0d1b496 100644
--- a/services/univention-ldb-modules/third_party/waf/waflib/Configure.py
+++ b/services/univention-ldb-modules/third_party/waf/waflib/Configure.py
@@ -116,7 +116,7 @@ class ConfigurationContext(Context.Context):
 		if not out:
 			out = getattr(Context.g_module, Context.OUT, None)
 		if not out:
-			out = Options.lockfile.replace('.lock-waf_%s_' % sys.platform, '').replace('.lock-waf', '')
+			out = Options.lockfile.replace('.lock-waf_%s_' % sys.platform, '').replace('.lock-waf', '').replace('.lock-wscript', '')

 		# someone can be messing with symlinks
 		out = os.path.realpath(out)
diff --git a/services/univention-ldb-modules/third_party/waf/waflib/extras/review.py b/services/univention-ldb-modules/third_party/waf/waflib/extras/review.py
index 561e06219d..65fb77fa92 100644
--- a/services/univention-ldb-modules/third_party/waf/waflib/extras/review.py
+++ b/services/univention-ldb-modules/third_party/waf/waflib/extras/review.py
@@ -144,7 +144,7 @@ class ReviewContext(Context.Context):
 		if not out:
 			out = getattr(Context.g_module, Context.OUT, None)
 		if not out:
-			out = Options.lockfile.replace('.lock-waf', '')
+			out = Options.lockfile.replace('.lock-waf', '').replace('.lock-wscript', '')
 		self.build_path = (os.path.isabs(out) and self.root or self.path).make_node(out).abspath()
 		"""Path to the build directory"""