fix[updater]: Handle non-blocking components
`Updater.get_all_available_release_updates()` returns a 2-tuple
`(release, components)`, where `blocking_components` can be `None`.

> # python2 -c 'from univention.updater.tools import UniventionUpdater as U;u=U();print(u.get_all_available_release_updates())'
> (['5.0-0'], None)

If any UCS included component is installed, which is *not* available for
UCS 5.0-0 (e.g. `pykota`, `nagios-server`), they are reported as
"blocking" by AppC:

> # univention-app update-check --ucs-version 5.0-0
...
> The update to 5.0-0 is currently not possible, because the following Apps are not available for UCS 5.0-0:
>  * Print server Quota (pykota)

Those are added to `blocking_components`, which crashes with a traceback
as `blocking_components` is None:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/univention/management/console/modules/updater/__init__.py", line 456, in status
>     blocking_components.update(set(blocking_apps))
> AttributeError: 'NoneType' object has no attribute 'update'

Make sure `blocking_components` is an (empty) `set()` instead of `None`.

Reproducer: `umc-command -U Administrator -P univention updater/updates/get`

Bug #53228