feat(umc): add error handling for threads trying to write the  HTTP response
instead of a crashed thread we at least log the exception.
This will help developers recognize the cause of the error.
Responses must be answered in the main thread.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/adtakeover/__init__.py", line 78, in _background
    self.finished(request.id, result, status=status, message=message)
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 448, in finished
    self.result(res)
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 455, in result
    request._request_handler.reply(response)
  File "/usr/lib/python3/dist-packages/univention/management/console/modserver.py", line 384, in reply
    self.finish(body)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1052, in finish
    future = self.flush(include_footers=True)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 994, in flush
    start_line, self._headers, chunk, callback=callback)
  File "/usr/lib/python3/dist-packages/tornado/http1connection.py", line 409, in write_headers
    future = self._write_future = Future()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.

Bug #43633