feat(ucslint): provide entrypoint script
for backwards compatibility if someone executes the script from git.
and because the testframework otherwise breaks since the pathlib migration with:

FAILED[arg]
Traceback (most recent call last):
  File "packaging/ucslint/univention/ucslint/main.py", line 437, in <module>
    main()
  File "packaging/ucslint/univention/ucslint/main.py", line 429, in main
    incident_cnt, exitcode_cnt = chk.printResult(ignore_IDs, display_only_IDs, options.display_only_categories, options.exitcode_categories, options.junit_xml)
  File "packaging/ucslint/univention/ucslint/main.py", line 216, in printResult
    if self.in_overrides(msg):
  File "packaging/ucslint/univention/ucslint/main.py", line 178, in in_overrides
    filepath = msg.filename.relative_to(self.path) if msg.filename else Path("")
AttributeError: 'str' object has no attribute 'relative_to'

Bug #55668