build(umc): deactivate automatic unit tests
As adding missing build dependencies on UDM will cause a cyclic
depdendency, not satisfiable by initial package import and our gitlab
pipeline order detection.

make[1]: Leaving directory '/var/build/temp/tmpvrr67jqy/univention-management-console-15.0.1'
   dh_auto_test -O--buildsystem=pybuild
I: pybuild base:311: cd /var/build/temp/tmpvrr67jqy/univention-management-console-15.0.1/.pybuild/cpython3_3.13_univention-management-console/build; python3.13 -m unittest discover -v·
univention.management.console.modules (unittest.loader._FailedTest.univention.management.console.modules) ... ERROR

======================================================================
ERROR: univention.management.console.modules (unittest.loader._FailedTest.univention.management.console.modules)
----------------------------------------------------------------------
ImportError: Failed to import test module: univention.management.console.modules
Traceback (most recent call last):
  File "/usr/lib/python3.13/unittest/loader.py", line 429, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.13/unittest/loader.py", line 339, in _get_module_from_name
    __import__(name)
    ~~~~~~~~~~^^^^^^
  File "/var/build/temp/tmpvrr67jqy/univention-management-console-15.0.1/.pybuild/cpython3_3.13_univention-management-console/build/univention/management/console/modules/__init__.py", line 11, in <module>
    from univention.management.console.base import *  # noqa: E402,F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/build/temp/tmpvrr67jqy/univention-management-console-15.0.1/.pybuild/cpython3_3.13_univention-management-console/build/univention/management/console/base.py", line 90, in <module>
    import univention.admin.uexceptions as udm_errors
ModuleNotFoundError: No module named 'univention.admin'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
E: pybuild pybuild:389: test: plugin distutils failed with: exit code=1: cd /var/build/temp/tmpvrr67jqy/univention-management-console-15.0.1/.pybuild/cpython3_3.13_univention-management-console/build; python3.13 -m unittest discover -v·
dh_auto_test: error: pybuild --test -i python{version} -p 3.13 returned exit code 13

Bug #59418