Bug #99999 French: Cleanup translation
debian/*.dirs: Remove unneeded file

debian/control: Remove runtime dependency on UMC

debian/control: Update description

debian/compat: v7 is no longer supported with Debian-10-Buster

Makefile: Use `install` instead of `mkdir` and `mv`.

FYI: If you see this traceback during install time

> # ucr set ucs/server/languages/fr_FR?"Français"
> Traceback (most recent call last):
>   File "/usr/sbin/ucr", line 69, in <module>
>     ub.main(convertToUtf8(sys.argv[1:]))
>   File "/usr/lib/python2.7/dist-packages/univention/config_registry/frontend.py", line 792, in main
>     result = handler_func(args, cmd_opts)
>   File "/usr/lib/python2.7/dist-packages/univention/config_registry/frontend.py", line 166, in handler_set
>     changed = ucr.update(changes)
>   File "/usr/lib/python2.7/dist-packages/univention/config_registry/backend.py", line 194, in __exit__
>     self.save()
>   File "/usr/lib/python2.7/dist-packages/univention/config_registry/backend.py", line 158, in save
>     registry.save()
>   File "/usr/lib/python2.7/dist-packages/univention/config_registry/backend.py", line 625, in save
>     self.__save_file(filename)
>   File "/usr/lib/python2.7/dist-packages/univention/config_registry/backend.py", line 594, in __save_file
>     reg_file.write(self.__unicode__())
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 84: ordinal not in range(128)
> > /usr/lib/python2.7/dist-packages/univention/config_registry/backend.py(594)__save_file()
> -> reg_file.write(self.__unicode__())
> (Pdb) p reg_file.name
> '/etc/univention/base.conf.bak.temp'
> (Pdb) p self
> {'locale': 'fr_FR.UTF-8:UTF-8', 'ucr/encoding/strict': 'true', 'ucs/server/languages/fr_FR': 'Fran\xc3\xa7ais'}
> (Pdb) l
> 614                                                     reg_file.write('# univention_ base.conf\n\n')
> 615                                                     reg_file.write(self.__unicode__())
> 616                     except EnvironmentError as ex:
> 617                             # suppress certain errors
> 618                             if ex.errno != errno.EACCES:
> 619  ->                                 raise

it happens because your non-UCS-system is missing /etc/python2.7/sitecustomize.py:
> import sys
> # the sys module must be reloaded otherwise setdefaultencoding is unknown
> reload(sys)
> sys.setdefaultencoding('utf8')