test(ppolicy): make crypt hash comparision future-proof
The debug output is broken in case of failures.
The Python crypt module was deprecated in Python 3.11 (PEP 594) and removed in Python 3.13.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import crypt, univention.uldap; lo = univention.uldap.getMachineConnection(); password = lo.getAttr('uid=lgztbcwv,cn=users,dc=AutoTest091,dc=test', 'userPassword')[0].decode('ASCII').replace('{crypt}', ''); print('Password valid?:', crypt.crypt('univention', password.rsplit('$', 1)[0]) == password)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'crypt'

Bug #59418