fix[udm] Dynamic module loading
when `univention.admin.modules.update()` is called during package build
time on a system, where UDM is already installed, the code will also
find extensions installed via `settings/udm_module` in
/usr/share/pyshared/ or /usr/lib/python*/dist-packages/.
But they will fail to import when `PYTHONPATH=modules` is used: In that
case only the specified local directory is used, *not* the system
directories. But the code still tries to iterate then, finds the file,
but then fails to import.

> 122     >>> univention.admin.modules.update()
> UNEXPECTED EXCEPTION: ModuleNotFoundError("No module named 'univention.admin.handlers.portals'")
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/doctest.py", line 1329, in __run
>     compileflags, 1), test.globs)
>   File "<doctest univention.admin.syntax.update_choices[1]>", line 1, in <module>
>   File "/root/univention-directory-manager-modules/modules/univention/admin/modules.py", line 148, in update
>     _walk(root, w_root, w_files)
>   File "/root/univention-directory-manager-modules/modules/univention/admin/modules.py", line 132, in _walk
>     m = importlib.import_module('univention.admin.handlers.%s' % (modulepackage,))  # type: Any
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
>
> ModuleNotFoundError: No module named 'univention.admin.handlers.portals'

Change the directory walking code to use only the directories of
`univention.admin.handlers`.

Bug #31857