Bug #53430: Fix TypeError during ldif mode
Traceback (most recent call last):
  File "/usr/lib/univention-directory-listener/system/replication.py", line 923, in handler
    _modify_object_from_old_and_new(lo, dn, old, new)
  File "/usr/lib/univention-directory-listener/system/replication.py", line 747, in _modify_object_from_old_and_new
    lo.modify_s(dn, ml)
  File "/usr/lib/univention-directory-listener/system/replication.py", line 506, in modify_s
    self.__new_entry(dn)
  File "/usr/lib/univention-directory-listener/system/replication.py", line 485, in __new_entry
    self.__print_attribute('dn', dn.encode('UTF-8'))
  File "/usr/lib/univention-directory-listener/system/replication.py", line 480, in __print_attribute
    print(value[0:60 - pos], file=self.fp)
TypeError: a bytes-like object is required, not 'str'