fix[uvmm]: prevent AttributeError when syntax class is not registered yet
During a `univention-directory-listener-ctrl resync udm_extension` (on upgrade to UCS 5.0)
all UDM extensions are loaded in arbitrary order. This causes failing import
if a UDM module is handled before the required UDM syntax class exists.

Therefore a fallback syntax class is used.

Traceback (most recent call last):
  File "/usr/lib/univention-directory-listener/system/udm_extension.py", line 203, in handler
    udm_modules.update()
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 121, in update
    _walk(root, w_root, w_files)
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 105, in _walk
    m = importlib.import_module('univention.admin.handlers.%s' % (modulepackage,))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/uvmm/info.py", line 88, in <module>
    syntax=udm_syntax.UvmmProfiles,
AttributeError: module 'univention.admin.syntax' has no attribute 'UvmmProfiles'

Traceback (most recent call last):
  File "/usr/lib/univention-directory-listener/system/udm_extension.py", line 203, in handler
    udm_modules.update()
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 121, in update
    _walk(root, w_root, w_files)
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 105, in _walk
    m = importlib.import_module('univention.admin.handlers.%s' % (modulepackage,))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/uvmm/profile.py", line 153, in <module>
    syntax=udm_syntax.UvmmCapacity,
AttributeError: module 'univention.admin.syntax' has no attribute 'UvmmCapacity'

Bug #51955