fix(univention-fix-ucr-dns): DNS @ unjoined memberserver
> Traceback (most recent call last):
>   File "DNS/Base.py", line 323, in req
>     self.sendUDPRequest(server)
>   File "DNS/Base.py", line 376, in sendUDPRequest
>     raise first_socket_error
>   File "DNS/Base.py", line 351, in sendUDPRequest
>     r=self.processUDPReply()
>   File "DNS/Base.py", line 135, in processUDPReply
>     (self.reply, self.from_address) = self.s.recvfrom(65535)
> ConnectionRefusedError: [Errno 111] Connection refused
>
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/usr/share/univention-server/univention-fix-ucr-dns", line 564, in <module>
>     main()
>   File "/usr/share/univention-server/univention-fix-ucr-dns", line 91, in main
>     add_self(nameservers, ucr, options.own_ip)
>   File "/usr/share/univention-server/univention-fix-ucr-dns", line 339, in add_self
>     if not options.force_self and not query_master_src_record(domain, myself):
>   File "/usr/share/univention-server/univention-fix-ucr-dns", line 495, in query_master_src_record
>     res = req.req()
>   File "DNS/Base.py", line 327, in req
>     raise SocketError(reason)
> DNS.Base.SocketError: [Errno 111] Connection refused

Catch exception when calling `query_master_src_record`.

Remove timestamp from log message: Will be added by `journald` anyway.

Increase with for `CRITICAL`.

Print function name instead of full logger path.

Move IP address validation into ArgumentParser.

Fix type annotation for `add_self()`.

Bug #56750