Bug #52044: fix sync_to_ucs() not putting AD:mail to UCS:mailPrimaryAddress
_object_mapping_con() depends on the order of post_attributes being processed.
In Python 3 the order of dict keys changed, therefore 'proxyAddresses' was before 'mail'.
We want that UCS['mailPrimaryAddress'] contains the value of AD['proxyAddresses']. ('mail' should only be mapped into 'mailAlternativeAddress'.)

As 'mail' also maps to mailPrimaryAddress (via post_attributes.con_attribute) the ucs_object['mailPrimaryAddress'] is set twice.

We are working around this by sorting the attributes, which hopefully is the only case where the order is important.
Unsure: A different fix might be to evaluate the sync_mode of the attribute? Or fix that broken mapping definition.

'mailPrimaryAddress': univention.connector.attribute(
»   ucs_attribute='mailPrimaryAddress',
»   ldap_attribute='mailPrimaryAddress',
»   con_attribute='proxyAddresses',
»   mapping=(
»   »   proxyAddresses.to_proxyAddresses,
»   »   proxyAddresses.to_mailPrimaryAddress
»   ),
»   compare_function=proxyAddresses.equal,
),
'mailPrimaryAddress_to_mail': univention.connector.attribute(
»   sync_mode='write',
»   ucs_attribute='mailPrimaryAddress',
»   ldap_attribute='mailPrimaryAddress',
»   con_attribute='mail',
),
'mailAlternativeAddress': univention.connector.attribute(
»   sync_mode='read' if configRegistry.is_true('connector/ad/mapping/user/primarymail') else 'sync',  # proxyAddresses.to_mailPrimaryAddress does the write
»   ucs_attribute='mailAlternativeAddress',
»   ldap_attribute='mailAlternativeAddress',
»   con_attribute='proxyAddresses',
»   mapping=(
»   »   None,
»   »   proxyAddresses.to_mailAlternativeAddress
»   ),
»   compare_function=proxyAddresses.equal,
),

The bug caused the following traceback and made 231read_ad_user_change_mail_attributes and 130sync_ucs_user_change_mail_attributes fail:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/connector/__init__.py", line 1375, in sync_to_ucs
    result = self.modify_in_ucs(property_type, object, module, position)
  File "/usr/lib/python3/dist-packages/univention/connector/__init__.py", line 1154, in modify_in_ucs
    res = ucs_object.modify(serverctrls=serverctrls, response=response)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1400, in modify
    return super(object, self).modify(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 641, in modify
    dn = self._modify(modify_childs, ignore_license=ignore_license, response=response)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1311, in _modify
    self._call_checkLdap_on_all_property_syntaxes()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1672, in _call_checkLdap_on_all_property_syntaxes
    prop.syntax.checkLdap(self.lo, self.info.get(pname))
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 2134, in checkLdap
    raise univention.admin.uexceptions.valueError(self.errMsgDomain % (', '.join(faillist),))
univention.admin.uexceptions.valueError: The domain part of the primary mail address is not in list of configured mail domains: private2@external.org