Bug #24393: Fix UMC default argv
Traceback (most recent call last):
  File "./univention-management-console-web-server", line 617, in <module>
    http_daemon = UMC_HTTP_Daemon()
  File "./univention-management-console-web-server", line 529, in __init__
    sys.argv[ 1 ] = 'start'
IndexError: list assignment index out of range

Overwrite all remaining arguments instead of only the first.

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.0/ucs@28967 1b283449-9f2f-0410-b571-8eb228e1a901