fix(udm-rest): abort authorization if authentication failed
force_authorization stopped the request via self.finish() instead of
raising an exception. Therefore the authorize() method was called, which
couldn't do anything as no user information were set.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1712, in _execute
    result = self.prepare()
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 163, in prepare
    self.authorize(authorization)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 241, in authorize
    self._auth_check_allowed_groups(allowed_groups)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 245, in _auth_check_allowed_groups
    if self.request.username in ('cn=admin',):
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HTTPServerRequest' object has no attribute 'username'

Fixes: 7b4d79ec409ac6f7696553d07176cc4e66269065
Bug #59176