Bug #51907: fix crash in users/user if mailPrimaryAddress property default value is set in open()
Reproducer:
import univention.admin.modules
lo, po = univention.admin.uldap.getMachineConnection()
univention.admin.modules.update()
u = univention.admin.modules.get('users/user')
univention.admin.modules.init(lo, po, u)
us = u.object(None, lo, po)
us['mailPrimaryAddress']
us.open()
print(us.info)
us['username'] = 'fbest'
us['lastname'] = 'fbest'
us['mailPrimaryAddress'] = 'fbest@localhost'
us.create()

Traceback (most recent call last):
  File "repr.py", line 13, in <module>
    us.create()
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/__init__.py", line 554, in create
    self._ldap_pre_ready()
  File "/usr/lib/python2.7/dist-packages/univention/admin/handlers/users/user.py", line 1616, in _ldap_pre_ready
    if self['mailPrimaryAddress'] and self['mailPrimaryAddress'].lower() != self.oldinfo.get('mailPrimaryAddress', '').lower():
AttributeError: 'NoneType' object has no attribute 'lower'