fix(udm dns): fix object description when object doesn't exists
which makes it impossible to get template for dns/reverse_zone and
dns/ptr_record for creation.
Reproducer:
curl https://Administrator:univention@demo.univention.de/univention/udm/dns/reverse_zone/add -i
curl https://Administrator:univention@demo.univention.de/univention/udm/dns/ptr_record/add -i

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1595, in _execute
    result = yield result
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/univention/admin/rest/sanitizer.py", line 188, in decorator
    return await method(self, *self.path_args, **self.path_kwargs, **self.request.decoded_query_arguments, **self.request.body_arguments)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2398, in get
    result.update(self.get_create_form(module, template=template, position=position, superordinate=superordinate))
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2447, in get_create_form
    result.update(Object.get_representation(module, obj, ['*'], self.ldap_connection, copy, True))
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 1842, in get_representation
    props['id'] = module.obj_description(obj)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/udm_ldap.py", line 853, in obj_description
    description = udm_objects.description(obj)
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 156, in description
    return object.description()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/dns/reverse_zone.py", line 259, in description
    rdn_value = ldap.dn.str2dn(self.dn)[0][0][1].encode('UTF-8')
IndexError: list index out of range

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1595, in _execute
    result = yield result
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/univention/admin/rest/sanitizer.py", line 188, in decorator
    return await method(self, *self.path_args, **self.path_kwargs, **self.request.decoded_query_arguments, **self.request.body_arguments)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2398, in get
    result.update(self.get_create_form(module, template=template, position=position, superordinate=superordinate))
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2447, in get_create_form
    result.update(Object.get_representation(module, obj, ['*'], self.ldap_connection, copy, True))
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 1842, in get_representation
    props['id'] = module.obj_description(obj)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/udm_ldap.py", line 861, in obj_description
    description = udm_objects.description(obj)
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 156, in description
    return object.description()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/dns/ptr_record.py", line 169, in description
    return calc_ip(self.info['address'], self.superordinate.info['subnet']).compressed
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/dns/ptr_record.py", line 121, in calc_ip
    parts = rev.split('.')
AttributeError: 'NoneType' object has no attribute 'split'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1595, in _execute
    result = yield result
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3/dist-packages/univention/admin/rest/sanitizer.py", line 188, in decorator
    return await method(self, *self.path_args, **self.path_kwargs, **self.request.decoded_query_arguments, **self.request.body_arguments)
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2398, in get
    result.update(self.get_create_form(module, template=template, position=position, superordinate=superordinate))
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2447, in get_create_form
    result.update(Object.get_representation(module, obj, ['*'], self.ldap_connection, copy, True))
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 1842, in get_representation
    props['id'] = module.obj_description(obj)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/udm/udm_ldap.py", line 861, in obj_description
    description = udm_objects.description(obj)
  File "/usr/lib/python3/dist-packages/univention/admin/objects.py", line 156, in description
    return object.description()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1228, in description
    return syntax.tostring(self[name])
  File "/usr/lib/python3/dist-packages/univention/admin/syntax.py", line 632, in tostring
    return self.delimiter.join(texts)
TypeError: can only join an iterable

Bug #55555