Bug #52942: fix wait_for_activation() waiting for the actual file
wait_for_activation() currently waited for the file to be registered to
be present, which is always the case.

Calculate a approximate file path the listener will write the UDM
extension to. Wait 60 seconds for the file to be present.
Also try to import registered UDM modules to proove their existance.

Waiting for activation of the extension object univention-portal: OK
Waiting for activation of the extension object 62univention-portal: OK
Waiting for activation of the extension object univention-portal: OK
Waiting for file /usr/lib/univention-portal/syntax/univention-portal.py: OK
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Object exists: cn=udm_module,cn=univention,dc=autotest076,dc=local
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/univention/lib/ldap_extension.py", line 1507, in <module>
    commands[sys.argv.pop(1)]()
  File "/usr/lib/python3/dist-packages/univention/lib/ldap_extension.py", line 1392, in ucs_registerLDAPExtension
    univentionUDMModule.register(udm_module, opts, udm_passthrough_options)
  File "/usr/lib/python3/dist-packages/univention/lib/ldap_extension.py", line 1064, in register
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/univention-portal/udm/portal.py", line 97, in <module>
    syntax=univention.admin.syntax.NewPortalFontColor,
AttributeError: module 'univention.admin.syntax' has no attribute 'NewPortalFontColor'