Bug #49129: fix missing flush() method
Exception ignored in: <univention.config_registry.filters.Output object at 0x7fb256d06908>
AttributeError: 'Output' object has no attribute 'flush'