fix(umc): fix UCR template when (default) value is set
Since git:27e041f043fe956fde72c6e992062177e9d4acfd a default value for
umc/http/processes/start-port is set but the UCR template doesn't
convert it to "int" causing:
File: /etc/apache2/sites-available/univention.conf
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
TypeError: unsupported operand type(s) for +: 'int' and 'str'

Bug #55726