fix(ad-connector): fix AD-Connector configuration
Another exception which is masked by some wrong error message.

12.06.23 10:58:18.732  MODULE      ( ERROR   ) : well-known-sid-object-rename failed with 1 (Traceback (most recent call last):
  File "/usr/share/univention-ad-connector/scripts/well-known-sid-object-rename", line 52, in <module>
    import univention.connector.ad
  File "/usr/lib/python3/dist-packages/univention/connector/ad/__init__.py", line 64, in <module>
    import univention.connector.ad.mapping
  File "/usr/lib/python3/dist-packages/univention/connector/ad/mapping.py", line 42, in <module>
    import univention.connector.ad.password
  File "/usr/lib/python3/dist-packages/univention/connector/ad/password.py", line 44, in <module>
    import Crypto
ModuleNotFoundError: No module named 'Crypto'
)
__ERR__:Could not connect to AD Server WIN-DUA7EARHMN9.admember.test. Please verify that username and password are correct.
W: The config registry variable 'kerberos/kdc' does not exist

The cause is git:85fa3834fe27d38575ac2d1e86bfcf0d2c20ca78, which removed python3-crypto as dependency from univention-squid. It's unused there.
But univention-ad-connector doesn't have the dependency.

Bug #56137