fix(udm): fix LDAP search with pure attributes and delegative administration enabled
Since Bug #59579 git:ddb499961a7d1af15f5db346b6c2d40136dd8ca8 the UDM
REST API search for `opened=0` uses `lo.search(…, attr=['entryUUID', 'univentionObjectType'])`.

With delegative administration, the search results are first tried to be
decoded to a UDM object used for evaluating read permissions and then
filtered for all readable properties.
We now ignore unmapped properties in the LDAP attributes result set and
make them "readable" by default.
Additionally, since Bug #59217
git:9c15b7a008c374f5f79c7e0e2fd91b556ee328bf `entryUUID` is a property
of the module and therefor needs to grant read access as well.

The error signature otherwise looks like:

`GET /udm/users/user/?position=uid%3Dyvlc2ju3or%2Ccn%3Dusers%2Cou%3Dou1%2Cdc%3Ducs%2Cdc%3Dtest&scope=base&hidden=0&properties=dn&opened=0`
→
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1735, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/rest/sanitizer.py", line 178, in decorator
    return await method(self, *self.path_args, **self.path_kwargs, **self.request.decoded_query_arguments, **self.request.body_arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 1582, in get
    entry = Object.get_dn_representation(module, dn, attrs, self.ldap_connection)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/admin/rest/module.py", line 2010, in get_dn_representation
    'uuid': attrs['entryUUID'][0].decode('ASCII'),
            ~~~~~^^^^^^^^^^^^^
KeyError: 'entryUUID'
```

Bug #59673