fix(checks/pkgver): Skip broken version comparison
> Traceback (most recent call last):
>   File "30_compare_package_versions.py", line 15, in <module>
>     from urllib import urlopen, urlretrieve
> ImportError: cannot import name 'urlopen' from 'urllib' (/usr/lib/python3.7/urllib/__init__.py)

Actually the test is broken since UCS 5.0 as the repository layout
changed to `pool/` and `dists/`, so the "get releases by following the
directory structure" on the download severs fails.

Fixes: c91cfa42e2a6323f09922153b663e09ce62648fe
Bug #55715