Bug #49838: add binary attributes to DECODE_IGNORELIST
Otherwise
1. values are decoded to unicode strings while they must be bytestring

LDAP        (INFO   ): sync_from_ucs: The current S4 values: set([u'Mozilla Firefox (ach)'])
LDAP        (INFO   ): to modify: cn=bd0fe548-f1fd-4b53-9f41-1bf8f984c03c,cn=packages,cn=class store,cn=machine,cn={4f038446-6064-43e8-80e1-dcf60721166e},cn=policies,cn=system,DC=school,DC=dev
LDAP        (ERROR  ): sync_from_ucs: traceback during modify object: cn=bd0fe548-f1fd-4b53-9f41-1bf8f984c03c,cn=packages,cn=class store,cn=machine,cn={4f038446-6064-43e8-80e1-dcf60721166e},cn=policies,cn=system,DC=school,DC=dev
LDAP        (ERROR  ): sync_from_ucs: traceback due to modlist: [(2, 'productCode', [u'P\x18\x85\x1d\x13\xb9\xb8H\x9f\xcb\x02\xb39v:\xb8']), (0, 'upgradeProductCode', set([u'\xf4\x06\x8c\x12N\xa0\xa6O\x93\x97T)Q3\x96\xed']))]
LDAP        (WARNING): sync failed, saved as rejected
LDAP        (WARNING): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/__init__.py", line 891, in __sync_file_from_ucs
    if ((old_dn and not self.sync_from_ucs(key, mapped_object, pre_mapped_ucs_dn, unicode(old_dn, 'utf8'), old, new)) or (not old_dn and not self.sync_from_ucs(key, mapped_object, pre_mapped_ucs_dn, old_dn, old, new))):
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/s4/__init__.py", line 2610, in sync_from_ucs
    self.lo_s4.lo.modify_ext_s(compatible_modstring(object['dn']), compatible_modlist(modlist), serverctrls=self.serverctrls_for_add_and_modify)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 373, in modify_ext_s
    msgid = self.modify_ext(dn,modlist,serverctrls,clientctrls)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 370, in modify_ext
    return self._ldap_call(self._l.modify_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 106, in _ldap_call
    result = func(*args,**kwargs)
TypeError: ('expected a string in the list', u'P\x18\x85\x1d\x13\xb9\xb8H\x9f\xcb\x02\xb39v:\xb8')

2. values are .decode('utf-8').encode('latin-1') ed
LDAP        (INFO   ): to modify: cn=bd0fe548-f1fd-4b53-9f41-1bf8f984c03c,cn=packages,cn=class store,cn=machine,cn={4f038446-6064-43e8-80e1-dcf60721166e},cn=policies,cn=system,DC=school,DC=dev
LDAP        (ERROR  ): sync_from_ucs: traceback during modify object: cn=bd0fe548-f1fd-4b53-9f41-1bf8f984c03c,cn=packages,cn=class store,cn=machine,cn={4f038446-6064-43e8-80e1-dcf60721166e},cn=policies,cn=system,DC=school,DC=dev
LDAP        (ERROR  ): sync_from_ucs: traceback due to modlist: [(2, 'productCode', ['P\x18\xc2\x85\x1d\x13\xc2\xb9\xc2\xb8H\xc2\x9f\xc3\x8b\x02\xc2\xb39v:\xc2\xb8']), (0, 'upgradeProductCode', set(['\xc3\xb4\x06\xc2\x8c\x12N\xc2\xa0\xc2\xa6O\xc2\x93\xc2\x97T)Q3\xc2\x96\xc3\xad']))]
LDAP        (WARNING): sync failed, saved as rejected
LDAP        (WARNING): Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/__init__.py", line 891, in __sync_file_from_ucs
    if ((old_dn and not self.sync_from_ucs(key, mapped_object, pre_mapped_ucs_dn, unicode(old_dn, 'utf8'), old, new)) or (not old_dn and not self.sync_from_ucs(key, mapped_object, pre_mapped_ucs_dn, old_dn, old, new))):
  File "/usr/lib/python2.7/dist-packages/univention/s4connector/s4/__init__.py", line 2610, in sync_from_ucs
    self.lo_s4.lo.modify_ext_s(compatible_modstring(object['dn']), compatible_modlist(modlist), serverctrls=self.serverctrls_for_add_and_modify)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 374, in modify_ext_s
    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 514, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 521, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/lib/python2.7/dist-packages/ldap/ldapobject.py", line 106, in _ldap_call
    result = func(*args,**kwargs)
INVALID_SYNTAX: {'info': "0000200B: objectclass_attrs: attribute 'productCode' on entry 'cn=bd0fe548-f1fd-4b53-9f41-1bf8f984c03c,cn=packages,cn=class store,cn=machine,cn={4f038446-6064-43e8-80e1-dcf60721166e},cn=policies,cn=system,DC=school,DC=dev' contains at least one invalid value!", 'desc': 'Invalid syntax'}