Bug #55959: fix UMC-Server crashes when status is given as request argument
requesting /univention/auth?status=XXX causes a crash of UMC server and UMC web server:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 194, in sanitize_args
    return sanitizer.sanitize(name, args)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/sanitizers.py", line 209, in sanitize
    new_value = self._sanitize(value, name, further_arguments)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/sanitizers.py", line 314, in _sanitize
    raise multi_error
univention.management.console.modules.sanitizers.MultiValidationError: 2 error(s) occurred

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 351, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 254, in execute
    function.__func__(self, request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 998, in handle
    self._handle_auth(request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/session.py", line 1015, in _handle_auth
    }), 'request', {'request': request.body})
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/decorators.py", line 202, in sanitize_args
    raise UnprocessableEntity(str(exc), result=exc.result())
univention.management.console.error.UnprocessableEntity: 2 error(s) occurred

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/univention-management-console-server", line 162, in <module>
    umc_daemon.run()
  File "/usr/sbin/univention-management-console-server", line 114, in run
    notifier.loop()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 306, in loop
    step()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 292, in step
    if cond & condition and fd in __sockets[cond] and not __sockets[cond][fd](sock_obj):
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/server.py", line 168, in _receive
    state.session.execute('handle', msg)
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 259, in execute
    self.__error_handling(request, method, *sys.exc_info())
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 383, in __error_handling
    self.finished(request.id, result, message, status=status, headers=headers, error=error, reason=reason)
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 449, in finished
    res = Response(request)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 322, in __init__
    self.status = request.status
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 208, in <lambda>
    status = property(lambda self: self._get_key('status'), lambda self, value: self._set_key('status', value, int))
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 181, in _set_key
    self.body[key] = cast(value)
ValueError: invalid literal for int() with base 10: 'XXX'

MAIN        ( ERROR   ) : FATAL error: Traceback (most recent call last):
  File "/usr/sbin/univention-management-console-web-server", line 1581, in run
    notifier.loop()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 306, in loop
    step()
  File "/usr/lib/python3/dist-packages/notifier/nf_generic.py", line 292, in step
    if cond & condition and fd in __sockets[cond] and not __sockets[cond][fd](sock_obj):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/client.py", line 349, in _recv
    self.signal_emit('closed')
  File "/usr/lib/python3/dist-packages/notifier/signals.py", line 87, in signal_emit
    self.__signals[signal].emit(*args)
  File "/usr/lib/python3/dist-packages/notifier/signals.py", line 50, in emit
    if cb(*args):
       ^^^^^^^^^
  File "/usr/sbin/univention-management-console-web-server", line 223, in _closed
    response = Response(request)
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 322, in __init__
    self.status = request.status
    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 208, in <lambda>
    status = property(lambda self: self._get_key('status'), lambda self, value: self._set_key('status', value, int))
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/message.py", line 181, in _set_key
    self.body[key] = cast(value)
                     ^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'XXX'

Setting the response status from a request.status is a unused feature, which we can simply removed.