Bug #31494: fix replacing of filter if it's not a string
Request: udm/remove (networks/network)

  File "/usr/lib/pymodules/python2.7/notifier/threads.py", line 78, in _run
    tmp = self._function()
  File "/usr/lib/pymodules/python2.7/notifier/__init__.py", line 104, in __call__
    return self._function( *tmp, **self._kwargs )
  File "/usr/lib/pymodules/python2.7/univention/management/console/modules/udm/__init__.py", line 455, in _thread
    module.remove(ldap_dn, options.get('cleanup', False), options.get('recursive', False))
  File "/usr/lib/pymodules/python2.7/univention/management/console/modules/udm/udm_ldap.py", line 86, in _decorated
    return method(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/univention/management/console/ldap.py", line 143, in _decorated
    result = func(*args, **kwargs)
  File "/usr/lib/pymodules/python2.7/univention/management/console/modules/udm/udm_ldap.py", line 577, in remove
    obj.remove(remove_childs=recursive)
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/__init__.py", line 857, in remove
    return self._remove(remove_childs)
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/__init__.py", line 1506, in _remove
    self._ldap_post_remove()
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/networks/network.py", line 247, in _ldap_post_remove
    for computer in univention.admin.handlers.computers.computer.lookup(self.co, self.lo, filter_s=filter_):
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/computers/computer.py", line 157, in lookup
    res.extend(computer.lookup(co, lo, filter_s, base, superordinate, scope, unique, required, timeout, sizelimit))
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/computers/ipmanagedclient.py", line 305, in lookup
    filter_s = univention.admin.handlers.dns.alias.lookup_alias_filter(lo, filter_s)
  File "/usr/lib/pymodules/python2.7/univention/admin/handlers/dns/alias.py", line 168, in lookup_alias_filter
    if 'dnsAlias' not in filter_s:
TypeError: argument of type 'expression' is not iterable