Bug #51103: Fix create-32k-users-in-group
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "./create-32k-users-in-groups", line 220, in <module>
    main()
  File "./create-32k-users-in-groups", line 216, in main
    generator.create(groups)
  File "./create-32k-users-in-groups", line 175, in create
    self.group_members(group)
  File "./create-32k-users-in-groups", line 138, in group_members
    r_type, r_data = rrr
ValueError: too many values to unpack

Also convert to print_function