Bug #37289 test: Fix Jenkins regression
> Traceback (most recent call last):
>   File "05_get_client_ip_address", line 48, in <module>
>     main()
>   File "05_get_client_ip_address", line 28, in main
>     username = ldap.explode_rdn(usernamd_dn)[0].split('=', 1)[-1]
> NameError: global name 'ldap' is not defined

import ldap

git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-4.0/ucs-4.0-0@57223 1b283449-9f2f-0410-b571-8eb228e1a901