Bug #50092 UVMM: Ignore certain errors
If a node updates its list of VMs while a migration is in progress,
there is concurrency issue between getting the list of VMs and fetching
the details: The VM may already be gone when the later happens:

> 2019-09-17 12:34:12,928 - uvmmd.node - WARNING - 'qemu://hdmi3.phahn.dev/system' broken? next check in 0:00:30.000. Domain not found: no domain with matching uuid '1c2d92e9-d9fc-4c92-a6c3-b7e95412ec0d' (ucs44)
> Traceback (most recent call last):
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/node.py", line 845, in update_autoreconnect
>     self.update()
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/node.py", line 1133, in update
>     domStat.update(dom)
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/node.py", line 379, in update
>     self.update_expensive(domain)
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/node.py", line 385, in update_expensive
>     cache_id = hash(dom.inactive_xml)
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/node.py", line 260, in inactive_xml
>     self._inactive_xml = self.domain.XMLDesc(libvirt.VIR_DOMAIN_XML_SECURE | libvirt.VIR_DOMAIN_XML_INACTIVE)
>   File "/usr/lib/python2.7/dist-packages/libvirt.py", line 492, in XMLDesc
>     if ret is None: raise libvirtError ('virDomainGetXMLDesc() failed', dom=self)
> libvirtError: Domain not found: no domain with matching uuid '1c2d92e9-d9fc-4c92-a6c3-b7e95412ec0d' (ucs44)

This exception is currently caught by update_autoreconnect(), which
interprets any libvirtError as a problem with the connection. The
connection is therefore closes and re-opened by the time.

But this races with the migration thread, which tries to access the
target host using that closed connection:

> 2019-09-17 12:34:18,046 - uvmmd.unix - ERROR - [744] Exception:
> Traceback (most recent call last):
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/unix.py", line 148, in handle_command
>     res = cmd(self, command)
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/commands.py", line 486, in DOMAIN_MIGRATE
>     node.domain_migrate(request.uri, request.domain, request.target_uri, request.mode)
>   File "/usr/lib/pymodules/python2.7/univention/uvmm/node.py", line 2145, in domain_migrate
>     assert target_conn is not None
> AssertionError

Teach Node.update() and Node.update_autoreconnect() to ignore errors for
missing domains and restrict the later to only reset the connection for
RPC related issues.

Keep closing the connection as a last resort if the problem persists.