test(utils): Workaround update-ca-certificates
Versions of update-ca-certificates before Debian-12-Bookworm remove
/etc/ssl/certs/ca-certificates.crt building the new bundle and moving it
to that location. This might take some time as the file system cache is
cold during boot and other processes start up. During that time the file
is missing and any process using it might fail. This happens to
`/usr/share/univention-updater/univention-updater-check` started by
`/etc/cron.d/univention-updater-check` at `@reboot` time:

> Traceback (most recent call last):
>   File "/usr/sbin/univention-upgrade", line 445, in do_update
>     update_available = performUpdate(options, checkForUpdates=options.check, silent=False)
>   File "/usr/sbin/univention-upgrade", line 141, in performUpdate
>     if func(options, checkForUpdates, silent):
>   File "/usr/sbin/univention-upgrade", line 272, in do_app_updates
>     app_upgrade_search.call()
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/__init__.py", line 220, in call
>     return obj.call_with_namespace(namespace)
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/__init__.py", line 226, in call_with_namespace
>     result = self.main(namespace)
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/upgrade_search.py", line 52, in main
>     get_action('update').call()
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/__init__.py", line 220, in call
>     return obj.call_with_namespace(namespace)
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/__init__.py", line 226, in call_with_namespace
>     result = self.main(namespace)
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/update.py", line 87, in main
>     if self._download_apps(app_cache):
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/update.py", line 180, in _download_apps
>     if self._download_files(app_cache, filenames):
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/update.py", line 159, in _download_files
>     new_etag = self._download_file(server, filename, cache_dir, etag, ucs_version)
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/__init__.py", line 58, in _func
>     return func(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/actions/update.py", line 214, in _download_file
>     response = urlopen(request)
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/utils.py", line 325, in urlopen
>     return urllib_request.urlopen(request, timeout=60)
>   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/utils.py", line 312, in https_open
>     return self.do_open(HTTPSConnection, req)
>   File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
>     h.request(req.get_method(), req.get_selector(), req.data, headers)
>   File "/usr/lib/python2.7/httplib.py", line 1058, in request
>     self._send_request(method, url, body, headers)
>   File "/usr/lib/python2.7/httplib.py", line 1098, in _send_request
>     self.endheaders(body)
>   File "/usr/lib/python2.7/httplib.py", line 1054, in endheaders
>     self._send_output(message_body)
>   File "/usr/lib/python2.7/httplib.py", line 892, in _send_output
>     self.send(msg)
>   File "/usr/lib/python2.7/httplib.py", line 854, in send
>     self.connect()
>   File "/usr/lib/python2.7/dist-packages/univention/appcenter/utils.py", line 306, in connect
>     self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file, cert_reqs=ssl.CERT_REQUIRED, ca_certs="/etc/ssl/certs/ca-certificates.crt")
>   File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
>     ciphers=ciphers)
>   File "/usr/lib/python2.7/ssl.py", line 552, in __init__
>     self._context.load_verify_locations(ca_certs)
> IOError: [Errno 2] No such file or directory

Bug #49575