Bug #52018: open files with UTF-8 encoding
In case the locale is unset (C) files are opened in ASCII in python 3.

This causes different errors, e.g.:
System diagnostic module:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 359, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 198, in _recv
    self.handle(msg)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 266, in handle
    six.reraise(self.__init_etype, self.__init_exc, self.__init_etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 307, in handle
    self.__handler.init()
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 94, in init
    self.load()
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 129, in load
    self.modules[plugin] = Plugin(plugin)
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 265, in __init__
    self.load()
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/__init__.py", line 271, in load
    level=0
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/diagnostic/plugins/01_ssh_connection.py", line 20, in <module>
    ucr.load()
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 143, in load
    reg.load()
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 536, in load
    for line in reg_file:
  File "/usr/lib/python3.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 7744: ordinal not in range(128)

AD-Connector Jenkins Tests:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/management/console/base.py", line 359, in __error_handling
    six.reraise(etype, exc, etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 198, in _recv
    self.handle(msg)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 266, in handle
    six.reraise(self.__init_etype, self.__init_exc, self.__init_etraceback)
  File "/usr/lib/python3/dist-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/univention/management/console/protocol/modserver.py", line 307, in handle
    self.__handler.init()
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/adconnector/__init__.py", line 155, in init
    self.__update_status()
  File "/usr/lib/python3/dist-packages/univention/management/console/modules/adconnector/__init__.py", line 360, in __update_status
    ucr.load()
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 143, in load
    reg.load()
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 536, in load
    for line in reg_file:
  File "/usr/lib/python3.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4977: ordinal not in range(128)

App-Center apps.xml generation:
Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
  File "/usr/lib/python3/dist-packages/univention/appcenter/app_cache.py", line 48, in <module>
    from univention.appcenter.app import App
  File "/usr/lib/python3/dist-packages/univention/appcenter/app.py", line 48, in <module>
    from univention.appcenter.packages import get_package_manager, packages_are_installed
  File "/usr/lib/python3/dist-packages/univention/appcenter/packages.py", line 45, in <module>
    from univention.appcenter.utils import call_process
  File "/usr/lib/python3/dist-packages/univention/appcenter/utils.py", line 59, in <module>
    from univention.appcenter.ucr import ucr_get, ucr_keys
  File "/usr/lib/python3/dist-packages/univention/appcenter/ucr.py", line 41, in <module>
    _UCR.load()
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 143, in load
    reg.load()
  File "/usr/lib/python3/dist-packages/univention/config_registry/backend.py", line 532, in load
    if reg_file.readline() == '' or reg_file.readline() == '':
  File "/usr/lib/python3.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8052: ordinal not in range(128)