Revert "refactor(ucslint): PEP-484 type hints"
This reverts commit 8987cddfd0050282480e0c886fbd2229ca4132c2.

Python3.7 does not like modern syntax:

> # docker run --rm -ti -u "$UID" -v "$PWD:/work" -w /work python:3.7-slim-buster python3 ucslint
> Traceback (most recent call last):
>   File "ucslint", line 52, in <module>
>     import univention.ucslint.base as uub
>   File "/work/univention/ucslint/base.py", line 74, in <module>
>     MsgIds = dict[str, tuple[int, str]]
> TypeError: 'type' object is not subscriptable

Semi-works:
> docker run --rm -ti -u "$UID" -v "$PWD:/work" -w /work -e HOME=/tmp python:3.7-slim-buster sh -c 'pip install python-debian && ./testucslint.sh --color --verbose'

Bug #55668