TypeError: a bytes-like object is required, not 'str'
When running ./29_user_uidNumber_and_group_gidNumber_collision -f

You get:

Traceback (most recent call last):
  File "29_user_uidNumber_and_group_gidNumber_collision", line 106, in <module>
    FAILURES = [test() for test in TESTS if test()]
  File "29_user_uidNumber_and_group_gidNumber_collision", line 106, in <listcomp>
    FAILURES = [test() for test in TESTS if test()]
  File "29_user_uidNumber_and_group_gidNumber_collision", line 47, in consecutive_user_creation
    id_to_collide_with = get_max_id()
  File "29_user_uidNumber_and_group_gidNumber_collision", line 35, in get_max_id
    users = udm_modules.lookup('users/user', None, LO, base=base_dn, scope='sub')
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 913, in lookup
    tmpres = module.lookup(co, lo, filter, base=base, superordinate=superordinate, scope=scope, unique=unique, required=required, timeout=timeout, sizelimit=sizelimit)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 1741, in lookup
    result.append(cls(co, lo, None, dn=dn, superordinate=superordinate, attributes=attrs))
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 1280, in __init__
    univention.admin.handlers.simpleLdap.__init__(self, co, lo, position, dn, superordinate, attributes=attributes)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/__init__.py", line 236, in __init__
    if not univention.admin.modules.recognize(self.module, self.dn, self.oldattr):
  File "/usr/lib/python3/dist-packages/univention/admin/modules.py", line 682, in recognize
    return module.identify(dn, attr)
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/users/user.py", line 2350, in identify
    if '0' in attr.get('uidNumber', []) or '$' in attr.get('uid', [''])[0] or b'univentionHost' in attr.get('objectClass', []) or b'functional' in attr.get('univentionObjectFlag', []):